#!/usr/bin/env python3
"""
T-C11 — c11_diff_review_test.py: self-test for scripts/c11_diff_review.py.

Positive:
  P1  enumeration: clean/PENDING/DECIDED classification + node listing
  P2  fingerprint stability + consistency-check silence on a clean fixture
  P3  roundtrip guard passes on a generator-contract fixture
  P4  manual hunks: edge hunk body = the exact 3-line §18 promotion change;
      meta hunk = the exact 3-line file-level change
  P5  hunk application == full simulation (internal consistency)
  P6  approve --dry-run: exact command printed, NOTHING written, exit 0
  P7  approve-all --dry-run excludes PENDING without --include-pending
  P8  approve --except composition (dry-run)

Negative (all fail closed, nothing written):
  N1  unknown identity                     N6  AI --by rejected
  N2  out-of-range index                   N7  missing --by rejected
  N3  PART_OF identity refused             N8  malformed --date rejected
  N4  held-candidate identity refused      N9  real approve w/o bundle refused
  N5  REVIEW_REQUIRED identity refused     N10 hand-edited graph refused
                                           N11 status drift decisions<->graph

Real-repo smoke (read-only):
  R1  `list` exits 0 on the live store state and reports the session-48
      surface (0 actionable — the batch-1 verdicts are applied / 5
      not-actionable / 56 promotions recorded) — the batch-1 §18
      application completed the per-batch operator gate (28 batch-1
      CONFIRM edges promoted session 48; the 5 not-actionable rows are
      the 3 pilot operator HOLDs + the pilot RR + the settled batch RR).

Usage: python3 scripts/c11_diff_review_test.py
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import c11_diff_review as T  # noqa: E402

FAILS = []


def check(name: str, cond: bool, detail: str = ""):
    if cond:
        print(f"  PASS  {name}")
    else:
        print(f"  FAIL  {name}  {detail}")
        FAILS.append(name)


def expect_exit(name: str, code: int, fn, *a, **kw):
    try:
        rc = fn(*a, **kw)
        got = rc if isinstance(rc, int) else 0
    except SystemExit as e:
        got = e.code if isinstance(e.code, int) else (1 if e.code else 0)
    check(name, got == code, f"(expected exit {code}, got {got})")


# ---------------------------------------------------------------------------
# Fixture — built THROUGH the generator's serialization contract so the
# roundtrip guard is satisfied by construction.
# ---------------------------------------------------------------------------
HDR = ("# SyllabAI 4CH1 concept graph (pilot) — T-C11, graph-as-code "
       "(KNOWLEDGE_GRAPH_CONTEXT.md §8A.14, C11_ARCHITECTURE.md §10)\n"
       "# Generated by scripts/c11_concept_pilot.py from "
       "scripts/c11_pilot_decisions.yaml (the AI decision record).\n"
       "# DO NOT hand-edit: re-run the script. Provenance tier AI_SUGGESTED; "
       "validation gate = operator review (see meta.validation_gate).\n"
       "# Generation date pinned 2026-09-11 (deterministic contract; "
       "byte-identical re-runs).\n")

PROV = {"tier": "AI_SUGGESTED", "model_version": "GLM (Super Z agent, z.ai)",
        "extraction_pass": "c11-pilot-pass-1",
        "derivation_method": "DEFINITIONAL_DEPENDENCY",
        "derivation_notes": "fixture derivation notes.",
        "upstream": "T-C10 HUMAN_VALIDATED 4CH1-1.27 @ Notes (2026-09-11)",
        "generated_date": "2026-09-11"}


def edge(src, rel, tgt, quote, status="SUGGESTED", conf="high",
         ambiguity=None, od=None):
    e = {"source": src, "relation": rel, "target": tgt,
         "evidence": [{"kind": "NOTE",
                       "file": "notes/fixture-note.md", "quote": quote}],
         "provenance": dict(PROV), "confidence": conf,
         "validation_status": status}
    if ambiguity is not None:
        e["ambiguity_note"] = ambiguity
    if od:
        e["operator_decision"] = od
    e["version"] = 1
    e["created_at"] = "2026-09-11"
    return e


Q1 = "The mass of 1 mole of a substance is known as the molar mass"
Q2 = "One mole of any substance contains the same number of particles"
Q3 = "Yield is reduced because the reaction may be reversible"


def make_fixture(base: Path):
    (base / "notes").mkdir(parents=True)
    (base / "notes" / "fixture-note.md").write_text(
        f"Intro line.\n{Q1}\nMiddle line.\n{Q2}\n{Q3}\nTail line.\n",
        encoding="utf-8")

    edges = [
        edge("4CH1-CON-X", "PART_OF", "4CH1-1.27", Q1, ambiguity=None),
        edge("4CH1-CON-A", "REQUIRES_PREREQUISITE", "4CH1-CON-B", Q1,
             ambiguity=None),                                   # clean high
        edge("4CH1-CON-A", "REQUIRES_PREREQUISITE", "4CH1-CON-C", Q2,
             conf="medium", ambiguity="adjacency-grounded",
             od={"verdict": "PENDING", "presented_date": "2026-09-11",
                 "note": "fixture pending judgment"}),          # PENDING
        edge("4CH1-CON-G", "REQUIRES_PREREQUISITE", "4CH1-CON-LAW", Q3,
             status="REVIEW_REQUIRED",
             ambiguity="evidence-complete, semantics uncertain",
             od={"verdict": "HOLD", "decided_by": "operator",
                 "decided_date": "2026-09-11",
                 "note": "operator HOLD"}),                     # decided
        edge("4CH1-CON-Y", "PART_OF", "4CH1-1.28", Q2, ambiguity=None),
    ]
    counts = {"edges": len(edges), "part_of_edges": 2,
              "requires_prerequisite_edges": 3, "review_required_edges": 1}
    meta = {"task": "T-C11", "stage": "pilot", "curriculum_code": "4CH1-2017",
            "scope": "PILOT_FIXTURE",
            "spec_points": ["4CH1-1.27", "4CH1-1.28"],
            "generator": "scripts/c11_concept_pilot.py",
            "decision_record": "scripts/c11_pilot_decisions.yaml",
            "extraction_pass": "c11-pilot-pass-1",
            "model_version": "GLM (Super Z agent, z.ai)",
            "contract": "graph/reports/C11_ARCHITECTURE.md",
            "generated": "2026-09-11", "provenance_default": "AI_SUGGESTED",
            "validation_gate": "operator review",
            "edge_vocabulary": "fixture", "counts": counts}
    (base / "graph").mkdir(parents=True)
    (base / "graph" / "concept_edges.yaml").write_text(
        HDR + "\n" + yaml.safe_dump({"meta": meta, "edges": edges},
                                    **T.DUMP_KW), encoding="utf-8")

    nodes = [
        {"code": "4CH1-CON-A", "family": "CONCEPT", "title": "Concept A",
         "aliases": ["a"], "spec_points": [
             {"code": "4CH1-1.27", "role": "CORE", "evidence": [
                 {"kind": "NOTE", "file": "notes/fixture-note.md",
                  "quote": Q1}]}],
         "provenance": dict(PROV), "confidence": "high",
         "validation_status": "SUGGESTED", "version": 1,
         "created_at": "2026-09-11"},
        {"code": "4CH1-CON-B", "family": "CONCEPT", "title": "Concept B",
         "aliases": [], "spec_points": [
             {"code": "4CH1-1.28", "role": "CORE", "evidence": [
                 {"kind": "NOTE", "file": "notes/fixture-note.md",
                  "quote": Q2}]}],
         "provenance": dict(PROV), "confidence": "high",
         "validation_status": "SUGGESTED", "version": 1,
         "created_at": "2026-09-11"},
    ]
    nmeta = dict(meta, counts={"nodes": 2, "concepts": 2, "misconceptions": 0,
                               "part_of_edges": 2, "semantic_edges": 3})
    (base / "graph" / "concepts.yaml").write_text(
        HDR + "\n" + yaml.safe_dump({"meta": nmeta, "nodes": nodes},
                                    **T.DUMP_KW), encoding="utf-8")

    sp = {"code": "4CH1-1.27", "official_code": "1.27",
          "official_wording": "know that the mole (mol) is the unit for the "
                              "amount of a substance",
          "subsection": "a", "ordering": 27, "global_order": 27}
    sp2 = {"code": "4CH1-1.28", "official_code": "1.28",
           "official_wording": "understand how to carry out calculations "
                               "involving amount of substance",
           "subsection": "a", "ordering": 28, "global_order": 28}
    smeta = {"task": "T-C10", "generated": "2026-09-11",
             "counts": {"specification_points": 2}}
    (base / "graph" / "specification_points.yaml").write_text(
        HDR + "\n" + yaml.safe_dump(
            {"meta": smeta, "specification_points": [sp, sp2]},
            **T.DUMP_KW), encoding="utf-8")

    dec = {"meta": {"task": "T-C11", "extraction_pass": "c11-pilot-pass-1",
                    "model_version": "GLM (Super Z agent, z.ai)",
                    "generated_date": "2026-09-11"},
           "command_kinds": [], "nodes": nodes,
           "edges": [e for e in edges if e["relation"] != "PART_OF"],
           "held": [{"id": "HELD-F1", "candidate":
                     "REQUIRES_PREREQUISITE(4CH1-CON-A, 4CH1-CON-LAW)",
                     "status": "held", "failing_rules": ["FC-1"],
                     "anchor_quote": Q3, "anchor_file": "notes/fixture-note.md",
                     "rationale": "fixture"}]}
    (base / "scripts").mkdir(parents=True)
    (base / "scripts" / "c11_pilot_decisions.yaml").write_text(
        yaml.safe_dump(dec, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8")
    # session-47: the decision-record registry requires the batch-1 member to
    # exist; the fixture stages an EMPTY batch record (no batch content in
    # this fixture — the fixture graph IS the registry's full output)
    (base / "scripts" / "c11_batch1_decisions.yaml").write_text(
        yaml.safe_dump({"meta": {"task": "T-C11", "stage": "s16-batch-1",
                                   "extraction_pass": "c11-s16-batch-1",
                                   "generated_date": "2026-09-12",
                                   "model_version": "GLM (Super Z agent, z.ai)",
                                   "curriculum_code": "4CH1-2017",
                                   "scope": {"spec_points": [],
                                              "practicals": [],
                                              "notes": []},
                                   "contract": "fixture"},
                        "command_kinds": [], "nodes": [], "edges": [],
                        "held": []},
                       allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8")


# NOTE: the fixture decision-record edges carry an extra key
# (`operator_decision`) that the generated graph file intentionally omits —
# operator_decision blocks live decisions-side only and are never emitted
# into graph/*.yaml (architecture §7). The consistency check only compares
# identities + validation_status, so the fixture is consistent by design.


def apply_hunks(old_text: str, hunks: list) -> str:
    old = old_text.splitlines(keepends=True)
    out, pos = [], 0
    for h in hunks:
        m = re.match(r"@@ -(\d+),(\d+) \+\d+,\d+ @@", h[0])
        a_start, a_count = int(m.group(1)), int(m.group(2))
        out += old[pos:a_start - 1]
        pos = a_start - 1
        for l in h[1:]:
            if l.startswith("+") or l.startswith(" "):
                out.append(l[1:])
        pos += a_count
    out += old[pos:]
    return "".join(out)


def run_cli(argv, base: Path):
    import contextlib
    import io
    old_repo = T.REPO
    T.REPO = base
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            rc = T.main(argv)
    finally:
        T.REPO = old_repo
    return (rc if isinstance(rc, int) else 0), buf.getvalue()


def main() -> int:
    print("c11_diff_review_test")
    tmp = Path(tempfile.mkdtemp(prefix="c11diffreview-"))
    try:
        base = tmp / "fx"
        base.mkdir()
        make_fixture(base)

        st = T.load_state(base)
        print(" fixture state")
        check("P3 roundtrip guard", (T.roundtrip_guard(st), True)[1])
        check("P2 consistency silent", st["failures"] == [],
              str(st["failures"]))
        fp1, fp2 = T.fingerprint(st), T.fingerprint(T.load_state(base))
        check("P2 fingerprint stable", fp1 == fp2)

        pend = T.pending_items(st)
        act = T.actionable_edges(st)
        check("P1 pending == 2 (clean+PENDING)", len(pend) == 2, str(len(pend)))
        clean = [i for i in pend if not i["flag"]]
        flagged = [i for i in pend if i["flag"] == "PENDING"]
        check("P1 one clean one flagged", len(clean) == 1 and len(flagged) == 1)
        check("P1 HOLD edge not actionable",
              len(act) == 3 and all(a["flag"] == "DECIDED"
                                    for a in act if not a["actionable"]))
        check("P1 nodes listed", len(T.node_items(st)) == 2)

        ident = clean[0]["identity"]
        by, date = "operator", "2026-09-12"
        eh, mh = T.edge_hunks(st, ident, by, date)
        ebody = "".join(eh)
        check("P4 edge hunk removes SUGGESTED",
              "-  validation_status: SUGGESTED\n" in ebody)
        check("P4 edge hunk adds the 3-line §18 change",
              "+  validation_status: HUMAN_VALIDATED\n" in ebody
              and f"+  validated_by: {by}\n" in ebody
              and f"+  validated_date: '{date}'\n" in ebody)
        check("P4 keys land at validation_status position",
              ebody.index("+  validation_status:") <
              ebody.index("+  validated_by:") <
              ebody.index("+  validated_date:") <
              ebody.index("   version: 1"))
        mbody = "".join(mh)
        check("P4 meta hunk adds the 3-line file-level change",
              f"+    promoted_edges: 1\n" in mbody
              and f"+    human_validated_edges: 1\n" in mbody
              and "+  promotion_record: scripts/c11_promotions.yaml\n"
                  in mbody)

        old, new = T.simulate_promotion(st, [ident], by, date)
        check("P5 hunk application == full simulation",
              apply_hunks(old, [mh, eh]) == new)  # file order: meta first

        snap = (base / "graph" / "concept_edges.yaml").read_text()

        rc, out = run_cli(["approve", ident, "--by", by, "--date", date,
                           "--dry-run"], base)
        check("P6 dry-run exit 0", rc == 0)
        check("P6 dry-run prints the exact c11_promote command",
              "c11_promote.py --edge " + ident in out)
        check("P6 dry-run writes nothing",
              not (base / "scripts" / "c11_promotions.yaml").exists()
              and (base / "graph" / "concept_edges.yaml").read_text() == snap)

        rc, out = run_cli(["approve", "--all", "--by", by, "--date", date,
                           "--dry-run"], base)
        check("P7 approve-all excludes PENDING by default",
              "4CH1-CON-A REQUIRES_PREREQUISITE 4CH1-CON-C" not in out
              and "c11_promote.py --edge 4CH1-CON-A REQUIRES_PREREQUISITE "
                  "4CH1-CON-B" in out)
        rc, out = run_cli(["approve", "--all", "--include-pending", "--by", by,
                           "--date", date, "--dry-run"], base)
        check("P7 --include-pending selects the PENDING edge",
              "--edge 4CH1-CON-A REQUIRES_PREREQUISITE 4CH1-CON-C" in out)

        rc, out = run_cli(["approve", "--except", ident, "--by", by,
                           "--date", date, "--dry-run"], base)
        check("P8 --except removes the listed identity",
              ident not in out.split("c11_promote.py")[1])

        # --- negatives (fail closed, nothing written) -----------------------
        print(" fail-closed negatives")
        N = [("N1 unknown identity",
              ["approve", "4CH1-CON-NOPE REQUIRES_PREREQUISITE 4CH1-CON-B",
               "--by", by, "--dry-run"]),
             ("N2 out-of-range index", ["approve", "99", "--by", by,
                                        "--dry-run"]),
             ("N3 PART_OF refused",
              ["approve", "4CH1-CON-X PART_OF 4CH1-1.27", "--by", by,
               "--dry-run"]),
             ("N4 held candidate refused",
              ["approve", "4CH1-CON-A REQUIRES_PREREQUISITE 4CH1-CON-LAW",
               "--by", by, "--dry-run"]),
             ("N5 REVIEW_REQUIRED refused",
              ["approve", "4CH1-CON-G REQUIRES_PREREQUISITE 4CH1-CON-LAW",
               "--by", by, "--dry-run"]),
             ("N6 AI --by rejected",
              ["approve", ident, "--by", "Super Z", "--dry-run"]),
             ("N7 missing --by", ["approve", ident, "--dry-run"]),
             ("N8 bad --date",
              ["approve", ident, "--by", by, "--date", "12-09-2026",
               "--dry-run"])]
        for name, argv in N:
            expect_exit(name, 1, run_cli, argv, base)
        # N5 must resolve to the REVIEW_REQUIRED identity, not 'unknown'
        st2 = T.load_state(base)
        rr = [i for i in T.actionable_edges(st2) if i["flag"] == "DECIDED"
              and i["edge"]["validation_status"] == "REVIEW_REQUIRED"]
        check("N5 REVIEW_REQUIRED still pending-classified", len(rr) == 1)
        check("N9/N10 prerequisites still intact",
              not (base / "scripts" / "c11_promotions.yaml").exists()
              and (base / "graph" / "concept_edges.yaml").read_text() == snap)

        # N9: real (non-dry) approve without the ratifying bundle
        expect_exit("N9 real approve without bundle refused", 1, run_cli,
                    ["approve", ident, "--by", by, "--date", date], base)

        # N10: hand-edited graph (byte-level) -> roundtrip guard refusal
        (base / "graph" / "concept_edges.yaml").write_text(
            snap + "# stray hand-edit\n", encoding="utf-8")
        expect_exit("N10 hand-edited graph refused", 1, run_cli,
                    ["approve", ident, "--by", by, "--date", date,
                     "--dry-run"], base)
        (base / "graph" / "concept_edges.yaml").write_text(snap,
                                                           encoding="utf-8")

        # N11: validation_status drift decisions <-> graph
        idx = snap.index("\nmeta:\n")
        doc = yaml.safe_load(snap[idx + 1:])   # body incl. the `meta:` line
        for e in doc["edges"]:
            if (e["source"], e["relation"], e["target"]) == \
                    ("4CH1-CON-A", "REQUIRES_PREREQUISITE", "4CH1-CON-B"):
                e["validation_status"] = "REVIEW_REQUIRED"
        (base / "graph" / "concept_edges.yaml").write_text(
            snap[:idx + 1] + yaml.safe_dump(doc, **T.DUMP_KW),
            encoding="utf-8")
        expect_exit("N11 status drift refused", 1, run_cli,
                    ["approve", ident, "--by", by, "--date", date,
                     "--dry-run"], base)
        (base / "graph" / "concept_edges.yaml").write_text(snap,
                                                           encoding="utf-8")

        check("N* negatives wrote nothing",
              not (base / "scripts" / "c11_promotions.yaml").exists()
              and (base / "graph" / "concept_edges.yaml").read_text() == snap)

        # --- real-repo read-only smoke --------------------------------------
        print(" real-repo smoke (read-only)")
        r = subprocess.run([sys.executable, str(HERE / "c11_diff_review.py"),
                            "list"], cwd=T.REPO, capture_output=True, text=True)
        check("R1 list exits 0", r.returncode == 0, r.stderr[:200])
        # session-48 expectation: the batch-1 operator gate is SETTLED —
        # the "CONFIRM all" verdict round (scripts/c11_batch1_verdicts.yaml)
        # was applied through §18 (28 batch-1 edges promoted, store total
        # 56). The actionable surface is now empty; the 5 not-actionable
        # rows = 3 pilot operator HOLDs + the pilot RR + the settled
        # batch-1 RR (HOLD_REVIEW_REQUIRED).
        check("R1 reports 0 actionable / 5 not-actionable / 56 promotions",
              "actionable: 0  (clean 0 / pending-flagged 0)" in r.stdout
              and "not-actionable: 5" in r.stdout
              and "promo_count=56" in r.stdout)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print()
    if FAILS:
        print(f"FAIL: {len(FAILS)} test(s): {FAILS}")
        return 1
    print("ALL PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
