#!/usr/bin/env python3
"""
T-C09 — graph_check.py: validator for the Phase-1 graph-as-code output
(graph/*.yaml generated by scripts/c09_spec_graph_extract.py).

Validates, with zero core-repo dependencies:
  1. file/schema      — all six YAML files parse; every record carries the
                        required keys with the right types and vocabularies
  2. namespace        — every node code and every edge endpoint is in the
                        4CH1-* namespace; no foreign curriculum codes
                        (WPH-style unit codes, IAL) anywhere; 4SD0 is allowed
                        in prose only (Double-Award applicability rule, spec
                        PDF pp. 7/13/14), never as a node code
  3. provenance       — every record has complete provenance (tier, source
                        file, spec issue, extraction method, generator, date,
                        md-line anchor where the record class requires one)
  4. referential      — every edge endpoint resolves to a declared node; the
                        210 PART_OF edges exactly cover 28 subtopic->topic +
                        182 spec_point->subtopic; subtopic.spec_points equals
                        exactly the points declaring that subsection
  5. consistency      — counts in meta match the records; orderings are
                        unique and contiguous; damage flags and skill tags
                        come from the declared vocabularies; the official
                        PDF cross-check has zero mismatches
  6. notes-mapping    — T-C10 state: all 112 SME notes carry a spec_map
                        front-matter block (PROVIDER subsection anchor from
                        the source-URL slug + AI_SUGGESTED point mappings with
                        complete provenance); every mapped code is in the
                        182-point registry; every note has >=1 mapping; no
                        foreign curriculum codes in front matter; all 182
                        points covered; totals match the T-C10 baseline

Exit code 0 = all checks pass; 1 = failures (listed).
Usage: python3 scripts/graph_check.py [--graph DIR]
       python3 scripts/graph_check.py [--notes-root DIR]  (negative tests)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from c10_worksheets import parse_slug, SECTION_LETTERS  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
GRAPH_DEFAULT = REPO / "graph"
NOTES_ROOT_DEFAULT = REPO / "Chemistry IGCSE Revision Notes"

FILES = ["specification_points.yaml", "topics.yaml", "relationships.yaml",
         "command_words.yaml", "practicals.yaml", "assessment_objectives.yaml"]

GENERATOR = "scripts/c09_spec_graph_extract.py"
SOURCE_MD = "international-gcse-chemistry-2017-specification-2026-09-10_12-18-50.md"
SOURCE_PDF = "international-gcse-chemistry-2017-specification.pdf"

# --- T-C10 baseline (Phase 2 mapping state, 2026-09-11) -----------------------
C10_COUNTS = {"notes": 112, "mappings": 211, "points_covered": 182}
C10_CONFIDENCE = {"high", "medium", "low"}
C10_TIERS = {"PROVIDER", "AI_SUGGESTED"}

# --- expected counts (Phase-1 amended baseline) -------------------------------
COUNTS = {
    "spec_points": 182, "c_points": 52, "topics": 4, "subtopics": 28,
    "practicals": 12, "command_words": 25, "edges": 210, "papers": 2,
    "aos": 3,
}
PER_SECTION = {1: 60, 2: 50, 3: 22, 4: 50}

# --- vocabularies (must mirror the extractor; never invented here) -----------
LIVE_EDGE_ENUM = ["PART_OF", "REQUIRES_PREREQUISITE", "RELATED_TO",
                  "MISCONCEPTION_OF", "EXPLAINED_BY", "REMEDIATED_BY"]
SKILL_TAGS = {"PRACTICAL", "KNOW", "UNDERSTAND", "DESCRIBE", "EXPLAIN",
              "CALCULATE", "DRAW", "WRITE", "DEDUCE", "COMPARE",
              "INTERPRET", "PREDICT", "INVESTIGATE", "DETERMINE",
              "MEASURE", "RECALL"}
DAMAGE_FLAG_VOCAB = {
    "cjk-leak", "full-width-punct", "lost-subscript", "lost-superscript",
    "latex-fragment", "lost-space", "statement-continuation-row",
    "orphaned-outside-table", "code-space-damage",
    "superseded-truncated-table-row", "equation-rendered-as-latex-block",
    "subsection-reassigned-from-pdf", "subsection-header-missing-in-md",
    "ao-range-dash-missing", "unknown-leading-verb", "title-differs-md-vs-pdf",
}
ROW_SHAPES = {"two-col", "colspan-cell", "single-cell", "orphan-line"}
MATCH_LEVELS = {"exact", "normalized", "fuzzy", "mismatch", "pdf-missing"}
CW_CATEGORIES = {"main", "verb-preceding-command-word", "multiple-choice-questions"}
HEADER_SOURCES = {"md-table", "pdf-recovered"}
SECTION_TITLES = {1: "Principles of chemistry", 2: "Inorganic chemistry",
                  3: "Physical chemistry", 4: "Organic chemistry"}

RE_TOPIC_CODE = re.compile(r"^4CH1-S[1-4]$")
RE_SUBTOPIC_CODE = re.compile(r"^4CH1-S[1-4]-[a-i]$")
RE_POINT_CODE = re.compile(r"^4CH1-([1-4]\.\d{1,2}C?)$")
RE_CW_CODE = re.compile(r"^4CH1-CW-[A-Z0-9-]+$")
RE_PR_CODE = re.compile(r"^4CH1-PR-\d{2}$")
RE_AO_CODE = re.compile(r"^4CH1-AO[1-3]$")
RE_PAPER_CODE = re.compile(r"^4CH1-P[12]C$")
# foreign-curriculum leakage in prose: WPH11/WCH12-style unit codes, IAL,
# other 4-series subject codes. 4SD0 is whitelisted (Double Award context).
RE_FOREIGN = re.compile(r"\b(?:W[A-Z]{2}\d{1,2}|IAL|4SD0[^/]|4SC0|4CH0)\b")
RE_4SD0_ANY = re.compile(r"\b4SD0\b")

PROV_BASE_KEYS = ["tier", "source_file", "spec_issue", "extraction_method",
                  "generated_by", "generated_date"]


class Check:
    def __init__(self, name):
        self.name = name
        self.failures = []

    def fail(self, msg):
        self.failures.append(msg)

    @property
    def ok(self):
        return not self.failures


def is_int(x):
    return isinstance(x, int) and not isinstance(x, bool)


def check_provenance(chk, prov, ctx, want_line=False):
    if not isinstance(prov, dict):
        chk.fail(f"{ctx}: provenance is not a mapping")
        return
    for k in PROV_BASE_KEYS:
        if k not in prov or prov[k] in (None, ""):
            chk.fail(f"{ctx}: provenance missing '{k}'")
    if prov.get("tier") != "RULE_DERIVED":
        chk.fail(f"{ctx}: provenance tier '{prov.get('tier')}' != RULE_DERIVED")
    if prov.get("source_file") != SOURCE_MD:
        chk.fail(f"{ctx}: provenance source_file '{prov.get('source_file')}' != {SOURCE_MD}")
    if prov.get("spec_issue") != 3:
        chk.fail(f"{ctx}: provenance spec_issue != 3")
    if prov.get("generated_by") != GENERATOR:
        chk.fail(f"{ctx}: provenance generated_by != {GENERATOR}")
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", str(prov.get("generated_date", ""))):
        chk.fail(f"{ctx}: provenance generated_date not ISO: {prov.get('generated_date')!r}")
    if want_line:
        ln = prov.get("md_line")
        if not is_int(ln) or ln < 1:
            chk.fail(f"{ctx}: provenance md_line missing/not positive: {ln!r}")


def check_damage_flags(chk, flags, ctx):
    if not isinstance(flags, list):
        chk.fail(f"{ctx}: damage_flags is not a list")
        return
    for f in flags:
        if f not in DAMAGE_FLAG_VOCAB:
            chk.fail(f"{ctx}: damage flag '{f}' outside vocabulary")


def check_base_record(chk, rec, ctx):
    if rec.get("validation_status") != "RULE_DERIVED":
        chk.fail(f"{ctx}: validation_status '{rec.get('validation_status')}' != RULE_DERIVED")
    if rec.get("confidence") != 1.0:
        chk.fail(f"{ctx}: confidence {rec.get('confidence')!r} != 1.0")
    if rec.get("version") != 1:
        chk.fail(f"{ctx}: version {rec.get('version')!r} != 1")
    check_damage_flags(chk, rec.get("damage_flags"), ctx)


def scan_foreign(chk, value, ctx):
    """Prose fields may mention 4SD0 (Double-Award rule) but nothing foreign."""
    if not isinstance(value, str):
        return
    m = RE_FOREIGN.search(value)
    if m:
        chk.fail(f"{ctx}: foreign-curriculum token '{m.group(0)}' in text: {value[:100]!r}")


def load_all(graph_dir):
    data = {}
    for fn in FILES:
        p = graph_dir / fn
        if not p.exists():
            print(f"FATAL: missing {p}", file=sys.stderr)
            sys.exit(1)
        try:
            data[fn] = yaml.safe_load(p.read_text(encoding="utf-8"))
        except yaml.YAMLError as e:
            print(f"FATAL: {fn} does not parse: {e}", file=sys.stderr)
            sys.exit(1)
        if not isinstance(data[fn], dict) or "meta" not in data[fn]:
            print(f"FATAL: {fn} is not a mapping with a 'meta' key", file=sys.stderr)
            sys.exit(1)
    return data


def check_meta(data):
    chk = Check("meta")
    for fn, d in data.items():
        meta = d["meta"]
        for k in ("curriculum_code", "phase", "generator", "generated"):
            if k not in meta:
                chk.fail(f"{fn}: meta missing '{k}'")
        if meta.get("curriculum_code") != "4CH1-2017":
            chk.fail(f"{fn}: meta.curriculum_code '{meta.get('curriculum_code')}' != '4CH1-2017'")
        if meta.get("phase") != 1:
            chk.fail(f"{fn}: meta.phase != 1")
        if meta.get("generator") != GENERATOR:
            chk.fail(f"{fn}: meta.generator != {GENERATOR}")
        if meta.get("edge_vocabulary") and "PART_OF" not in meta["edge_vocabulary"]:
            chk.fail(f"{fn}: meta.edge_vocabulary lacks PART_OF")
    # counts vs records
    pts = data["specification_points.yaml"]["specification_points"]
    tops = data["topics.yaml"]["topics"]
    subs = data["topics.yaml"]["subtopics"]
    edges = data["relationships.yaml"]["edges"]
    cws = data["command_words.yaml"]["command_words"]
    prs = data["practicals.yaml"]["practicals"]
    aos = data["assessment_objectives.yaml"]["assessment_objectives"]
    papers = data["assessment_objectives.yaml"]["papers"]
    meta = data["specification_points.yaml"]["meta"].get("counts", {})
    expect = {
        "spec_points": len(pts), "c_points": sum(1 for p in pts if p.get("c_point")),
        "topics": len(tops), "subtopics": len(subs),
        "practicals": len(prs), "command_words": len(cws),
    }
    for k, v in expect.items():
        if meta.get(k) != v:
            chk.fail(f"meta.counts.{k} = {meta.get(k)!r} != actual {v}")
        if COUNTS.get(k) is not None and v != COUNTS[k]:
            chk.fail(f"actual {k} count {v} != expected {COUNTS[k]}")
    if len(edges) != COUNTS["edges"]:
        chk.fail(f"edges {len(edges)} != {COUNTS['edges']}")
    if len(aos) != COUNTS["aos"]:
        chk.fail(f"assessment objectives {len(aos)} != {COUNTS['aos']}")
    if len(papers) != COUNTS["papers"]:
        chk.fail(f"papers {len(papers)} != {COUNTS['papers']}")
    per_sec = {}
    for p in pts:
        per_sec[int(str(p["official_code"])[0])] = per_sec.get(int(str(p["official_code"])[0]), 0) + 1
    for sec, n in PER_SECTION.items():
        if per_sec.get(sec, 0) != n:
            chk.fail(f"section S{sec} has {per_sec.get(sec, 0)} points != {n}")
    return chk


def check_spec_points(data):
    chk = Check("specification_points")
    pts = data["specification_points.yaml"]["specification_points"]
    codes, gorders = set(), set()
    for i, p in enumerate(pts):
        ctx = f"point[{i}]"
        for k in ("code", "official_code", "official_wording", "section",
                  "subsection", "ordering", "global_order", "c_point",
                  "practical", "applicability", "leading_verb",
                  "draft_skill_tags", "validation_status", "confidence",
                  "version", "provenance", "damage_flags"):
            if k not in p:
                chk.fail(f"{ctx}: missing key '{k}'")
        m = RE_POINT_CODE.match(str(p.get("code", "")))
        if not m:
            chk.fail(f"{ctx}: code '{p.get('code')}' not in 4CH1-* point namespace")
            continue
        code = p["code"]
        if code in codes:
            chk.fail(f"{ctx}: duplicate code {code}")
        codes.add(code)
        if p.get("official_code") != m.group(1):
            chk.fail(f"{ctx}: official_code {p.get('official_code')!r} != {m.group(1)!r}")
        # namespace of structural refs
        if not RE_TOPIC_CODE.match(str(p.get("section", ""))):
            chk.fail(f"{code}: section '{p.get('section')}' not a 4CH1-S[1-4] topic code")
        if not RE_SUBTOPIC_CODE.match(str(p.get("subsection", ""))):
            chk.fail(f"{code}: subsection '{p.get('subsection')}' not a 4CH1-S[1-4]-[a-i] code")
        # c-point semantics
        c = str(p["official_code"]).endswith("C")
        if p.get("c_point") is not c:
            chk.fail(f"{code}: c_point {p.get('c_point')} != suffix semantics {c}")
        app = p.get("applicability", {})
        if not isinstance(app, dict):
            chk.fail(f"{code}: applicability not a mapping")
        else:
            if app.get("double_award_shared") is not False if c else app.get("double_award_shared") is not True:
                chk.fail(f"{code}: double_award_shared inconsistent with C-suffix")
            if app.get("papers") != (["2C"] if c else ["1C", "2C"]):
                chk.fail(f"{code}: applicability.papers {app.get('papers')} wrong for C={c}")
        # ordering
        if not is_int(p.get("ordering")) or p["ordering"] < 1:
            chk.fail(f"{code}: ordering {p.get('ordering')!r} not positive int")
        if not is_int(p.get("global_order")) or p["global_order"] < 1:
            chk.fail(f"{code}: global_order {p.get('global_order')!r} not positive int")
        elif p["global_order"] in gorders:
            chk.fail(f"{code}: duplicate global_order {p['global_order']}")
        gorders.add(p["global_order"])
        # skill tags
        tags = p.get("draft_skill_tags", [])
        if not isinstance(tags, list):
            chk.fail(f"{code}: draft_skill_tags not a list")
        else:
            for t in tags:
                mm = re.match(r"^4CH1-SK-([A-Z]+)$", str(t))
                if not mm or mm.group(1) not in SKILL_TAGS:
                    chk.fail(f"{code}: skill tag '{t}' outside vocabulary")
            if p.get("practical") and "4CH1-SK-PRACTICAL" not in tags:
                chk.fail(f"{code}: practical point lacks 4CH1-SK-PRACTICAL tag")
        # provenance
        prov = p.get("provenance", {})
        check_provenance(chk, prov, code, want_line=True)
        shape = prov.get("row_shape")
        if shape not in ROW_SHAPES:
            chk.fail(f"{code}: row_shape '{shape}' outside vocabulary")
        elif shape == "orphan-line":
            if prov.get("table_index") is not None or prov.get("row_index") is not None:
                chk.fail(f"{code}: orphan-line carries table/row indices")
        else:
            if not is_int(prov.get("table_index")) or not is_int(prov.get("row_index")):
                chk.fail(f"{code}: table_index/row_index missing for in-table row")
        xc = prov.get("pdf_crosscheck", {})
        if not isinstance(xc, dict):
            chk.fail(f"{code}: pdf_crosscheck not a mapping")
        else:
            if xc.get("file") != SOURCE_PDF:
                chk.fail(f"{code}: pdf_crosscheck.file != {SOURCE_PDF}")
            if not is_int(xc.get("page")) or xc.get("page", 0) < 1:
                chk.fail(f"{code}: pdf_crosscheck.page missing/not positive: {xc.get('page')!r}")
            if xc.get("match") not in MATCH_LEVELS:
                chk.fail(f"{code}: pdf_crosscheck.match '{xc.get('match')}' outside vocabulary")
            elif xc.get("match") in ("mismatch", "pdf-missing"):
                chk.fail(f"{code}: PDF cross-check match '{xc.get('match')}' — gate regression")
        # wording: verbatim + foreign scan (4SD0 allowed in applicability.rule only)
        if not isinstance(p.get("official_wording"), str) or not p["official_wording"].strip():
            chk.fail(f"{code}: official_wording empty")
        else:
            scan_foreign(chk, p["official_wording"], code)
        check_base_record(chk, p, code)
    if len(pts) != COUNTS["spec_points"]:
        chk.fail(f"point count {len(pts)} != {COUNTS['spec_points']}")
    if gorders and sorted(gorders) != list(range(1, len(pts) + 1)):
        chk.fail("global_order values are not exactly 1..N")
    return chk, codes


def check_topics(data, point_codes):
    chk = Check("topics")
    d = data["topics.yaml"]
    tops = d["topics"]
    subs = d["subtopics"]
    topic_codes = set()
    for i, t in enumerate(tops):
        ctx = f"topic[{i}]"
        if not RE_TOPIC_CODE.match(str(t.get("code", ""))):
            chk.fail(f"{ctx}: code '{t.get('code')}' not in 4CH1-S[1-4] namespace")
        else:
            sec = int(t["code"][-1])
            if t.get("title") != SECTION_TITLES.get(sec):
                chk.fail(f"{ctx}: title {t.get('title')!r} != canonical section title")
            if t.get("ordering") != sec:
                chk.fail(f"{ctx}: ordering {t.get('ordering')} != section number {sec}")
            topic_codes.add(t["code"])
        check_provenance(chk, t.get("provenance", {}), t.get("code", ctx), want_line=True)
        check_base_record(chk, t, t.get("code", ctx))
    if len(tops) != COUNTS["topics"]:
        chk.fail(f"topic count {len(tops)} != {COUNTS['topics']}")

    sub_codes = set()
    sub_members = {}
    for i, s in enumerate(subs):
        code = str(s.get("code", ""))
        ctx = f"subtopic[{i}] {code}"
        if not RE_SUBTOPIC_CODE.match(code):
            chk.fail(f"{ctx}: not in 4CH1-S[1-4]-[a-i] namespace")
            continue
        if code in sub_codes:
            chk.fail(f"{ctx}: duplicate subtopic code")
        sub_codes.add(code)
        if s.get("parent") != f"4CH1-S{code[-3]}":
            chk.fail(f"{ctx}: parent {s.get('parent')!r} inconsistent with code")
        if s.get("letter") != code[-1]:
            chk.fail(f"{ctx}: letter {s.get('letter')!r} != {code[-1]!r}")
        if s.get("header_source") not in HEADER_SOURCES:
            chk.fail(f"{ctx}: header_source '{s.get('header_source')}' outside vocabulary")
        if not isinstance(s.get("title"), str) or not s["title"].strip():
            chk.fail(f"{ctx}: PDF title missing")
        else:
            scan_foreign(chk, s["title"], ctx)
        members = s.get("spec_points", [])
        if not isinstance(members, list) or not members:
            chk.fail(f"{ctx}: spec_points list missing/empty")
            continue
        for ref in members:
            if ref not in point_codes:
                chk.fail(f"{ctx}: spec_points ref '{ref}' is not a declared spec point")
        if len(members) != len(set(members)):
            chk.fail(f"{ctx}: duplicate refs in spec_points")
        sub_members[code] = members
        if not is_int(s.get("ordering")) or s["ordering"] < 1:
            chk.fail(f"{ctx}: ordering not positive int")
        prov = s.get("provenance", {})
        check_provenance(chk, prov, code)
        if not is_int(prov.get("pdf_header_page")) or prov.get("pdf_header_page", 0) < 1:
            chk.fail(f"{ctx}: provenance pdf_header_page missing/not positive")
        if s.get("header_source") == "md-table" and not is_int(prov.get("md_line")):
            chk.fail(f"{ctx}: md-table header lacks provenance md_line")
        check_base_record(chk, s, ctx)

    # membership equivalence with the points' own declarations
    declared = {}
    for p in data["specification_points.yaml"]["specification_points"]:
        declared.setdefault(str(p.get("subsection")), []).append(p["code"])
    if sub_codes != set(declared):
        chk.fail(f"subtopic code set != subsections declared by points: "
                 f"only-in-subtopics={sorted(sub_codes - set(declared))} "
                 f"only-in-points={sorted(set(declared) - sub_codes)}")
    for code, members in sub_members.items():
        if sorted(members) != sorted(declared.get(code, [])):
            chk.fail(f"{code}: spec_points membership != points' declared subsection")
    # per-subsection ordering contiguity (1..n)
    pts = {p["code"]: p for p in data["specification_points.yaml"]["specification_points"]}
    for code, members in sub_members.items():
        orders = sorted(pts[m]["ordering"] for m in members if m in pts)
        if orders != list(range(1, len(orders) + 1)):
            chk.fail(f"{code}: per-subsection ordering not contiguous 1..n: {orders}")
    if len(subs) != COUNTS["subtopics"]:
        chk.fail(f"subtopic count {len(subs)} != {COUNTS['subtopics']}")
    return chk, topic_codes, sub_codes, sub_members


def check_relationships(data, point_codes, topic_codes, sub_codes, sub_members):
    chk = Check("relationships")
    edges = data["relationships.yaml"]["edges"]
    nodes = point_codes | topic_codes | sub_codes
    seen = set()
    sub_to_topic, point_to_sub = {}, {}
    for i, e in enumerate(edges):
        ctx = f"edge[{i}]"
        fr, rel, to = e.get("from"), e.get("relation"), e.get("to")
        if rel not in LIVE_EDGE_ENUM:
            chk.fail(f"{ctx}: relation '{rel}' not in live V2 knowledge_edges enum")
        if fr not in nodes:
            chk.fail(f"{ctx}: 'from' {fr!r} does not resolve to a declared node")
        if to not in nodes:
            chk.fail(f"{ctx}: 'to' {to!r} does not resolve to a declared node")
        key = (fr, rel, to)
        if key in seen:
            chk.fail(f"{ctx}: duplicate edge {key}")
        seen.add(key)
        if rel == "PART_OF":
            if fr in sub_codes:
                if to not in topic_codes:
                    chk.fail(f"{ctx}: subtopic PART_OF target {to!r} is not a topic")
                sub_to_topic[fr] = to
            elif fr in point_codes:
                if to not in sub_codes:
                    chk.fail(f"{ctx}: spec point PART_OF target {to!r} is not a subtopic")
                point_to_sub[fr] = to
            else:
                chk.fail(f"{ctx}: unexpected PART_OF source {fr!r}")
        if not is_int(e.get("order")) or e["order"] < 1:
            chk.fail(f"{ctx}: order not positive int")
        check_provenance(chk, e.get("provenance", {}), f"edge {fr}->{to}")
        check_base_record(chk, e, ctx)
    # exact coverage
    if sub_to_topic.keys() != sub_codes:
        chk.fail(f"PART_OF subtopic->topic coverage incomplete: missing "
                 f"{sorted(sub_codes - set(sub_to_topic))}")
    if point_to_sub.keys() != point_codes:
        missing = sorted(point_codes - set(point_to_sub))
        chk.fail(f"PART_OF point->subtopic coverage incomplete: {len(missing)} missing "
                 f"(first: {missing[:5]})")
    # agreement with declared structure
    pts = {p["code"]: p for p in data["specification_points.yaml"]["specification_points"]}
    for pc, sub in point_to_sub.items():
        if pts[pc].get("subsection") != sub:
            chk.fail(f"{pc}: edge target {sub} != declared subsection {pts[pc].get('subsection')}")
    subs = {s["code"]: s for s in data["topics.yaml"]["subtopics"]}
    for sc, tc in sub_to_topic.items():
        if subs[sc].get("parent") != tc:
            chk.fail(f"{sc}: edge target {tc} != declared parent {subs[sc].get('parent')}")
    # order fields follow the source structures
    for sc, members in sub_members.items():
        expected = {m: pts[m]["global_order"] for m in members}
        for e in edges:
            if e.get("from") in expected:
                if e.get("order") != expected[e["from"]]:
                    chk.fail(f"edge {e['from']}: order {e.get('order')} != global_order "
                             f"{expected[e['from']]}")
    return chk


def check_command_words(data):
    chk = Check("command_words")
    cws = data["command_words.yaml"]["command_words"]
    seen = set()
    for i, cw in enumerate(cws):
        ctx = f"cw[{i}]"
        code = str(cw.get("code", ""))
        if not RE_CW_CODE.match(code):
            chk.fail(f"{ctx}: code '{code}' not in 4CH1-CW-* namespace")
        if code in seen:
            chk.fail(f"{ctx}: duplicate code {code}")
        seen.add(code)
        if not isinstance(cw.get("command_word"), str) or not cw["command_word"].strip():
            chk.fail(f"{ctx}: command_word empty")
        if cw.get("category") not in CW_CATEGORIES:
            chk.fail(f"{ctx}: category '{cw.get('category')}' outside vocabulary")
        if not isinstance(cw.get("definition"), str) or not cw["definition"].strip():
            chk.fail(f"{ctx}: definition empty")
        else:
            scan_foreign(chk, cw["definition"], code)
        if cw.get("ordering") != i + 1:
            chk.fail(f"{ctx}: ordering {cw.get('ordering')} != position {i + 1}")
        prov = cw.get("provenance", {})
        check_provenance(chk, prov, code, want_line=True)
        if not is_int(prov.get("table_index")) or not is_int(prov.get("row_index")):
            chk.fail(f"{code}: provenance table_index/row_index missing")
        check_base_record(chk, cw, code)
    if len(cws) != COUNTS["command_words"]:
        chk.fail(f"command-word count {len(cws)} != {COUNTS['command_words']}")
    return chk


def check_practicals(data, point_codes):
    chk = Check("practicals")
    prs = data["practicals.yaml"]["practicals"]
    pts = {p["code"]: p for p in data["specification_points.yaml"]["specification_points"]}
    flagged = {p["code"] for p in pts.values() if p.get("practical")}
    covered = set()
    for i, pr in enumerate(prs):
        ctx = f"practical[{i}]"
        code = str(pr.get("code", ""))
        if not RE_PR_CODE.match(code):
            chk.fail(f"{ctx}: code '{code}' not in 4CH1-PR-## namespace")
        if pr.get("ordering") != i + 1:
            chk.fail(f"{ctx}: ordering {pr.get('ordering')} != position {i + 1}")
        sp = pr.get("spec_point")
        if sp not in point_codes:
            chk.fail(f"{ctx}: spec_point {sp!r} not a declared spec point")
        else:
            if sp not in flagged:
                chk.fail(f"{ctx}: spec_point {sp} is not practical-flagged")
            if sp in covered:
                chk.fail(f"{ctx}: spec_point {sp} covered twice")
            covered.add(sp)
            if pr.get("subsection") != pts[sp].get("subsection"):
                chk.fail(f"{ctx}: subsection {pr.get('subsection')!r} != point's "
                         f"{pts[sp].get('subsection')!r}")
        if not isinstance(pr.get("summary"), str) or not pr["summary"].strip():
            chk.fail(f"{ctx}: summary empty")
        prov = pr.get("provenance", {})
        check_provenance(chk, prov, code, want_line=True)
        check_base_record(chk, pr, code)
    if covered != flagged:
        chk.fail(f"practical coverage != practical-flagged points: missing "
                 f"{sorted(flagged - covered)}")
    if len(prs) != COUNTS["practicals"]:
        chk.fail(f"practical count {len(prs)} != {COUNTS['practicals']}")
    return chk


def check_assessment(data):
    chk = Check("assessment_objectives")
    d = data["assessment_objectives.yaml"]
    aos = d["assessment_objectives"]
    papers = d["papers"]
    for i, ao in enumerate(aos):
        code = str(ao.get("code", ""))
        if not RE_AO_CODE.match(code):
            chk.fail(f"ao[{i}]: code '{code}' not in 4CH1-AO[1-3] namespace")
        if not isinstance(ao.get("title"), str) or not ao["title"].strip():
            chk.fail(f"{code}: title empty")
        if not isinstance(ao.get("weighting_overall"), str):
            chk.fail(f"{code}: weighting_overall missing")
        wbp = ao.get("weighting_by_paper")
        if not isinstance(wbp, dict) or set(wbp) != {"paper_1", "paper_2"}:
            chk.fail(f"{code}: weighting_by_paper keys != paper_1/paper_2")
        else:
            for pk, pv in wbp.items():
                if not isinstance(pv, dict) or set(pv) != {"ao1", "ao2", "ao3"}:
                    chk.fail(f"{code}: weighting_by_paper.{pk} keys != ao1/ao2/ao3")
        check_provenance(chk, ao.get("provenance", {}), code)
        check_base_record(chk, ao, code)
    if len(aos) != COUNTS["aos"]:
        chk.fail(f"AO count {len(aos)} != {COUNTS['aos']}")

    seen = set()
    expected_codes = {"4CH1-P1C", "4CH1-P2C"}
    for i, p in enumerate(papers):
        ctx = f"paper[{i}]"
        code = str(p.get("code", ""))
        if not RE_PAPER_CODE.match(code):
            chk.fail(f"{ctx}: code '{code}' not in 4CH1-P[12]C namespace")
        if code in seen:
            chk.fail(f"{ctx}: duplicate paper code {code}")
        seen.add(code)
        if p.get("paper_code") not in ("4CH1/1C", "4CH1/2C"):
            chk.fail(f"{ctx}: paper_code {p.get('paper_code')!r} not a 4CH1 paper code")
        for k in ("marks", "duration_minutes"):
            if not is_int(p.get(k)) or p[k] < 1:
                chk.fail(f"{ctx}: {k} {p.get(k)!r} not a positive int")
        if not isinstance(p.get("weighting"), str) or not p["weighting"].endswith("%"):
            chk.fail(f"{ctx}: weighting {p.get('weighting')!r} not a percentage")
        if not isinstance(p.get("content_rule"), str) or not p["content_rule"].strip():
            chk.fail(f"{ctx}: content_rule empty")
        else:
            scan_foreign(chk, p["content_rule"], code)
        check_provenance(chk, p.get("provenance", {}), code, want_line=True)
        check_base_record(chk, p, code)
    if seen != expected_codes:
        chk.fail(f"paper codes {sorted(seen)} != {sorted(expected_codes)}")
    return chk


def check_namespace_prose(data):
    """4SD0 may appear ONLY in the applicability rule prose (Double Award)."""
    chk = Check("namespace_prose")
    pts = data["specification_points.yaml"]["specification_points"]
    for p in pts:
        rule = p.get("applicability", {}).get("rule", "")
        if isinstance(rule, str) and RE_4SD0_ANY.search(rule) and "Double Award" not in rule:
            chk.fail(f"{p['code']}: 4SD0 mentioned outside the Double-Award rule")
    return chk


def check_notes_mapping(data, point_codes, sub_codes, notes_root=None):
    """Check group 6 — T-C10 note->spec-point mapping state (front matter)."""
    chk = Check("c10-notes-mapping")
    notes_root = Path(notes_root) if notes_root else NOTES_ROOT_DEFAULT

    note_files = sorted(p for p in notes_root.rglob("*.md")
                        if "assets" not in p.parts)
    if len(note_files) != C10_COUNTS["notes"]:
        chk.fail(f"note count {len(note_files)} != {C10_COUNTS['notes']}")

    total_maps, covered = 0, set()
    n_notes = 0
    for path in note_files:
        rel = path.relative_to(notes_root.parent)
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        if not lines or lines[0].strip() != "---":
            chk.fail(f"c10.1 no front matter: {rel}")
            continue
        try:
            close = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
            fm = yaml.safe_load("\n".join(lines[1:close])) or {}
        except (StopIteration, yaml.YAMLError):
            chk.fail(f"c10.1 unparseable front matter: {rel}")
            continue
        sm = fm.get("spec_map")
        if not isinstance(sm, dict):
            chk.fail(f"c10.1 missing spec_map: {rel}")
            continue
        n_notes += 1
        # c10.1 schema
        for key in ("curriculum_code", "phase", "subsection", "spec_points",
                    "mapped_date", "mapper"):
            if key not in sm:
                chk.fail(f"c10.1 spec_map missing key {key}: {rel}")
        if sm.get("curriculum_code") != "4CH1-2017":
            chk.fail(f"c10.1 wrong curriculum_code {sm.get('curriculum_code')!r}: {rel}")
        # c10.4 PROVIDER anchor vs slug
        sub = sm.get("subsection")
        if sub not in sub_codes:
            chk.fail(f"c10.4 unknown subsection {sub!r}: {rel}")
        sp = sm.get("subsection_provenance", {})
        for key in ("tier", "signal", "slug", "validation_status"):
            if key not in sp:
                chk.fail(f"c10.4 subsection_provenance missing {key}: {rel}")
        if sp.get("tier") != "PROVIDER" or sp.get("signal") != "source-url-slug":
            chk.fail(f"c10.4 bad subsection provenance tier/signal: {rel}")
        url = fm.get("source") or ""
        parsed = parse_slug(url) if url else None
        if parsed:
            sec, grp, group_slug, _, _ = parsed
            want_sub = f"4CH1-S{sec}-{SECTION_LETTERS[grp - 1]}"
            if sub != want_sub:
                chk.fail(f"c10.4 anchor {sub} != slug-derived {want_sub}: {rel}")
            if sp.get("slug") != group_slug:
                chk.fail(f"c10.4 provenance slug {sp.get('slug')!r} != URL group "
                         f"{group_slug!r}: {rel}")
        # c10.5 mappings present, unique
        sps = sm.get("spec_points") or []
        if not sps:
            chk.fail(f"c10.5 zero mappings: {rel}")
        codes = [m.get("code") for m in sps]
        if len(codes) != len(set(codes)):
            chk.fail(f"c10.5 duplicate codes: {rel}")
        # c10.2 registry + c10.3 provenance completeness
        for m in sps:
            c = m.get("code")
            if c not in point_codes:
                chk.fail(f"c10.2 code not in 182-registry: {c} ({rel})")
            prov = m.get("provenance", {})
            if prov.get("tier") != "AI_SUGGESTED":
                chk.fail(f"c10.3 wrong tier {prov.get('tier')!r} for {c}: {rel}")
            if prov.get("confidence") not in C10_CONFIDENCE:
                chk.fail(f"c10.3 bad confidence {prov.get('confidence')!r} for {c}: {rel}")
            for key in ("model_version", "evidence", "rationale"):
                if not prov.get(key):
                    chk.fail(f"c10.3 missing {key} for {c}: {rel}")
            if prov.get("validation_status") != "SUGGESTED":
                chk.fail(f"c10.3 validation_status {prov.get('validation_status')!r} "
                         f"for {c}: {rel}")
            if c in point_codes:
                covered.add(c)
                total_maps += 1
        # c10.6 foreign codes in front matter (Wxx unit codes, 4CH0, IAL)
        fm_text = "\n".join(lines[1:close])
        for m in re.finditer(r"\b(W[A-Z]{2}\d{1,2}|4CH0|IAL|4SC0)\b", fm_text):
            chk.fail(f"c10.6 foreign curriculum code {m.group(1)!r} in front matter: {rel}")

    # c10.7 totals
    if n_notes != C10_COUNTS["notes"]:
        chk.fail(f"c10.7 notes with spec_map {n_notes} != {C10_COUNTS['notes']}")
    if total_maps != C10_COUNTS["mappings"]:
        chk.fail(f"c10.7 total mappings {total_maps} != {C10_COUNTS['mappings']}")
    if len(covered) != C10_COUNTS["points_covered"]:
        chk.fail(f"c10.7 covered points {len(covered)} != "
                 f"{C10_COUNTS['points_covered']}")
    return chk


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--graph", default=str(GRAPH_DEFAULT))
    ap.add_argument("--notes-root", default=str(NOTES_ROOT_DEFAULT))
    args = ap.parse_args()
    graph_dir = Path(args.graph)

    data = load_all(graph_dir)
    results = []
    results.append(check_meta(data))
    pt_chk, point_codes = check_spec_points(data)
    results.append(pt_chk)
    tp_chk, topic_codes, sub_codes, sub_members = check_topics(data, point_codes)
    results.append(tp_chk)
    results.append(check_relationships(data, point_codes, topic_codes, sub_codes,
                                        sub_members))
    results.append(check_command_words(data))
    results.append(check_practicals(data, point_codes))
    results.append(check_assessment(data))
    results.append(check_namespace_prose(data))
    results.append(check_notes_mapping(data, point_codes, sub_codes,
                                       notes_root=args.notes_root))

    total_fail = 0
    for chk in results:
        if chk.ok:
            print(f"PASS  {chk.name}")
        else:
            print(f"FAIL  {chk.name} ({len(chk.failures)} issue(s)):")
            for msg in chk.failures[:20]:
                print(f"      - {msg}")
            if len(chk.failures) > 20:
                print(f"      ... and {len(chk.failures) - 20} more")
            total_fail += len(chk.failures)
    print()
    if total_fail:
        print(f"graph_check: {total_fail} failure(s) across "
              f"{sum(1 for c in results if not c.ok)} check group(s).")
        sys.exit(1)
    n_points = len(point_codes)
    print(f"graph_check: ALL PASS — {n_points} spec points, "
          f"{len(topic_codes)} topics, {len(sub_codes)} subtopics, "
          f"{COUNTS['edges']} edges, {COUNTS['command_words']} command words, "
          f"{COUNTS['practicals']} practicals, {COUNTS['papers']} papers.")


if __name__ == "__main__":
    main()
