#!/usr/bin/env python3
"""
T-C09 — graph_check.py: validator for the Phase-1 graph-as-code output
(graph/*.yaml generated by scripts/c09_spec_graph_extract.py).

Validates, with zero core-repo dependencies:
  1. file/schema      — all six YAML files parse; every record carries the
                        required keys with the right types and vocabularies
  2. namespace        — every node code and every edge endpoint is in the
                        4CH1-* namespace; no foreign curriculum codes
                        (WPH-style unit codes, IAL) anywhere; 4SD0 is allowed
                        in prose only (Double-Award applicability rule, spec
                        PDF pp. 7/13/14), never as a node code
  3. provenance       — every record has complete provenance (tier, source
                        file, spec issue, extraction method, generator, date,
                        md-line anchor where the record class requires one)
  4. referential      — every edge endpoint resolves to a declared node; the
                        210 PART_OF edges exactly cover 28 subtopic->topic +
                        182 spec_point->subtopic; subtopic.spec_points equals
                        exactly the points declaring that subsection
  5. consistency      — counts in meta match the records; orderings are
                        unique and contiguous; damage flags and skill tags
                        come from the declared vocabularies; the official
                        PDF cross-check has zero mismatches
  6. notes-mapping    — T-C10 state: all 112 SME notes carry a spec_map
                        front-matter block (PROVIDER subsection anchor from
                        the source-URL slug + AI_SUGGESTED point mappings with
                        complete provenance); every mapped code is in the
                        182-point registry; every note has >=1 mapping; no
                        foreign curriculum codes in front matter; all 182
                        points covered; totals match the T-C10 baseline
 10. c11-concepts    — T-C11 pilot (phase 3): graph/concepts.yaml +
                        graph/spec_command_kinds.yaml — node schema, 4CH1
                        namespace, families/roles/states/confidence caps,
                        evidence anchors byte-verified (T-C10 norm),
                        attachment rule (SPEC quote inside the SP wording or
                        a NOTE whose T-C10 mapping to that SP is
                        HUMAN_VALIDATED), pilot scope + 4.15 negative
                        control, misconception source-quote gate, frozen
                        command-kind tags (guide §8)
 11. c11-concept-edges — T-C11 pilot: graph/concept_edges.yaml — relation
                        vocabulary, endpoint resolution (concepts ∪ pilot
                        SPs ∪ practicals), no self/duplicate edges, relation
                        discipline incl. the frozen §8A.11 misconception
                        triple distinction, REQUIRES_PREREQUISITE
                        acyclicity, PART_OF set == declared attachments,
                        anchor admissibility (NOTE anchors must resolve
                        through T-C10 HUMAN_VALIDATED coverage; MARK_SCHEME
                        anchors misconception-class only), anti-forgery
                        (no HUMAN_VALIDATED from generation; promoted edges
                        must match the operator-side promotion record
                        scripts/c11_promotions.yaml exactly — c11.13
                        validates that record and the frozen decision
                        record, always reading the REAL repo files so the
                        negative-test graph copies cannot cheat them)

Exit code 0 = all checks pass; 1 = failures (listed).
Usage: python3 scripts/graph_check.py [--graph DIR]
       python3 scripts/graph_check.py [--notes-root DIR]  (negative tests)
"""
from __future__ import annotations

import argparse
import re
import sys
import unicodedata
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from c10_worksheets import parse_slug, SECTION_LETTERS  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
GRAPH_DEFAULT = REPO / "graph"
NOTES_ROOT_DEFAULT = REPO / "Chemistry IGCSE Revision Notes"

FILES = ["specification_points.yaml", "topics.yaml", "relationships.yaml",
         "command_words.yaml", "practicals.yaml", "assessment_objectives.yaml"]

GENERATOR = "scripts/c09_spec_graph_extract.py"
SOURCE_MD = "international-gcse-chemistry-2017-specification-2026-09-10_12-18-50.md"
SOURCE_PDF = "international-gcse-chemistry-2017-specification.pdf"

# --- T-C10 baseline (Phase 2 mapping state, 2026-09-11) -----------------------
# Round-4 (2026-09-11): 2 mappings rejected & removed (4CH1-4.15 @ NOx,
# 4CH1-1.17 @ Calculate Relative Mass) — 211 -> 209 mappings, 182 -> 181
# covered points (4.15 = honest zero-coverage corpus gap; review sheet §12).
C10_COUNTS = {"notes": 112, "mappings": 209, "points_covered": 181}
C10_CONFIDENCE = {"high", "medium", "low"}
C10_TIERS = {"PROVIDER", "AI_SUGGESTED"}

# --- expected counts (Phase-1 amended baseline) -------------------------------
COUNTS = {
    "spec_points": 182, "c_points": 52, "topics": 4, "subtopics": 28,
    "practicals": 12, "command_words": 25, "edges": 210, "papers": 2,
    "aos": 3,
}
PER_SECTION = {1: 60, 2: 50, 3: 22, 4: 50}

# --- vocabularies (must mirror the extractor; never invented here) -----------
LIVE_EDGE_ENUM = ["PART_OF", "REQUIRES_PREREQUISITE", "RELATED_TO",
                  "MISCONCEPTION_OF", "EXPLAINED_BY", "REMEDIATED_BY"]
SKILL_TAGS = {"PRACTICAL", "KNOW", "UNDERSTAND", "DESCRIBE", "EXPLAIN",
              "CALCULATE", "DRAW", "WRITE", "DEDUCE", "COMPARE",
              "INTERPRET", "PREDICT", "INVESTIGATE", "DETERMINE",
              "MEASURE", "RECALL"}
DAMAGE_FLAG_VOCAB = {
    "cjk-leak", "full-width-punct", "lost-subscript", "lost-superscript",
    "latex-fragment", "lost-space", "statement-continuation-row",
    "orphaned-outside-table", "code-space-damage",
    "superseded-truncated-table-row", "equation-rendered-as-latex-block",
    "subsection-reassigned-from-pdf", "subsection-header-missing-in-md",
    "ao-range-dash-missing", "unknown-leading-verb", "title-differs-md-vs-pdf",
}
ROW_SHAPES = {"two-col", "colspan-cell", "single-cell", "orphan-line"}
MATCH_LEVELS = {"exact", "normalized", "fuzzy", "mismatch", "pdf-missing"}
CW_CATEGORIES = {"main", "verb-preceding-command-word", "multiple-choice-questions"}
HEADER_SOURCES = {"md-table", "pdf-recovered"}
SECTION_TITLES = {1: "Principles of chemistry", 2: "Inorganic chemistry",
                  3: "Physical chemistry", 4: "Organic chemistry"}

RE_TOPIC_CODE = re.compile(r"^4CH1-S[1-4]$")
RE_SUBTOPIC_CODE = re.compile(r"^4CH1-S[1-4]-[a-i]$")
RE_POINT_CODE = re.compile(r"^4CH1-([1-4]\.\d{1,2}C?)$")
RE_CW_CODE = re.compile(r"^4CH1-CW-[A-Z0-9-]+$")
RE_PR_CODE = re.compile(r"^4CH1-PR-\d{2}$")
RE_AO_CODE = re.compile(r"^4CH1-AO[1-3]$")
RE_PAPER_CODE = re.compile(r"^4CH1-P[12]C$")
# foreign-curriculum leakage in prose: WPH11/WCH12-style unit codes, IAL,
# other 4-series subject codes. 4SD0 is whitelisted (Double Award context).
RE_FOREIGN = re.compile(r"\b(?:W[A-Z]{2}\d{1,2}|IAL|4SD0[^/]|4SC0|4CH0)\b")
RE_4SD0_ANY = re.compile(r"\b4SD0\b")

PROV_BASE_KEYS = ["tier", "source_file", "spec_issue", "extraction_method",
                  "generated_by", "generated_date"]


class Check:
    def __init__(self, name):
        self.name = name
        self.failures = []

    def fail(self, msg):
        self.failures.append(msg)

    @property
    def ok(self):
        return not self.failures


def is_int(x):
    return isinstance(x, int) and not isinstance(x, bool)


def check_provenance(chk, prov, ctx, want_line=False):
    if not isinstance(prov, dict):
        chk.fail(f"{ctx}: provenance is not a mapping")
        return
    for k in PROV_BASE_KEYS:
        if k not in prov or prov[k] in (None, ""):
            chk.fail(f"{ctx}: provenance missing '{k}'")
    if prov.get("tier") != "RULE_DERIVED":
        chk.fail(f"{ctx}: provenance tier '{prov.get('tier')}' != RULE_DERIVED")
    if prov.get("source_file") != SOURCE_MD:
        chk.fail(f"{ctx}: provenance source_file '{prov.get('source_file')}' != {SOURCE_MD}")
    if prov.get("spec_issue") != 3:
        chk.fail(f"{ctx}: provenance spec_issue != 3")
    if prov.get("generated_by") != GENERATOR:
        chk.fail(f"{ctx}: provenance generated_by != {GENERATOR}")
    if not re.match(r"^\d{4}-\d{2}-\d{2}$", str(prov.get("generated_date", ""))):
        chk.fail(f"{ctx}: provenance generated_date not ISO: {prov.get('generated_date')!r}")
    if want_line:
        ln = prov.get("md_line")
        if not is_int(ln) or ln < 1:
            chk.fail(f"{ctx}: provenance md_line missing/not positive: {ln!r}")


def check_damage_flags(chk, flags, ctx):
    if not isinstance(flags, list):
        chk.fail(f"{ctx}: damage_flags is not a list")
        return
    for f in flags:
        if f not in DAMAGE_FLAG_VOCAB:
            chk.fail(f"{ctx}: damage flag '{f}' outside vocabulary")


def check_base_record(chk, rec, ctx):
    if rec.get("validation_status") != "RULE_DERIVED":
        chk.fail(f"{ctx}: validation_status '{rec.get('validation_status')}' != RULE_DERIVED")
    if rec.get("confidence") != 1.0:
        chk.fail(f"{ctx}: confidence {rec.get('confidence')!r} != 1.0")
    if rec.get("version") != 1:
        chk.fail(f"{ctx}: version {rec.get('version')!r} != 1")
    check_damage_flags(chk, rec.get("damage_flags"), ctx)


def scan_foreign(chk, value, ctx):
    """Prose fields may mention 4SD0 (Double-Award rule) but nothing foreign."""
    if not isinstance(value, str):
        return
    m = RE_FOREIGN.search(value)
    if m:
        chk.fail(f"{ctx}: foreign-curriculum token '{m.group(0)}' in text: {value[:100]!r}")


def load_all(graph_dir):
    data = {}
    for fn in FILES:
        p = graph_dir / fn
        if not p.exists():
            print(f"FATAL: missing {p}", file=sys.stderr)
            sys.exit(1)
        try:
            data[fn] = yaml.safe_load(p.read_text(encoding="utf-8"))
        except yaml.YAMLError as e:
            print(f"FATAL: {fn} does not parse: {e}", file=sys.stderr)
            sys.exit(1)
        if not isinstance(data[fn], dict) or "meta" not in data[fn]:
            print(f"FATAL: {fn} is not a mapping with a 'meta' key", file=sys.stderr)
            sys.exit(1)
    return data


def check_meta(data):
    chk = Check("meta")
    for fn, d in data.items():
        meta = d["meta"]
        for k in ("curriculum_code", "phase", "generator", "generated"):
            if k not in meta:
                chk.fail(f"{fn}: meta missing '{k}'")
        if meta.get("curriculum_code") != "4CH1-2017":
            chk.fail(f"{fn}: meta.curriculum_code '{meta.get('curriculum_code')}' != '4CH1-2017'")
        if meta.get("phase") != 1:
            chk.fail(f"{fn}: meta.phase != 1")
        if meta.get("generator") != GENERATOR:
            chk.fail(f"{fn}: meta.generator != {GENERATOR}")
        if meta.get("edge_vocabulary") and "PART_OF" not in meta["edge_vocabulary"]:
            chk.fail(f"{fn}: meta.edge_vocabulary lacks PART_OF")
    # counts vs records
    pts = data["specification_points.yaml"]["specification_points"]
    tops = data["topics.yaml"]["topics"]
    subs = data["topics.yaml"]["subtopics"]
    edges = data["relationships.yaml"]["edges"]
    cws = data["command_words.yaml"]["command_words"]
    prs = data["practicals.yaml"]["practicals"]
    aos = data["assessment_objectives.yaml"]["assessment_objectives"]
    papers = data["assessment_objectives.yaml"]["papers"]
    meta = data["specification_points.yaml"]["meta"].get("counts", {})
    expect = {
        "spec_points": len(pts), "c_points": sum(1 for p in pts if p.get("c_point")),
        "topics": len(tops), "subtopics": len(subs),
        "practicals": len(prs), "command_words": len(cws),
    }
    for k, v in expect.items():
        if meta.get(k) != v:
            chk.fail(f"meta.counts.{k} = {meta.get(k)!r} != actual {v}")
        if COUNTS.get(k) is not None and v != COUNTS[k]:
            chk.fail(f"actual {k} count {v} != expected {COUNTS[k]}")
    if len(edges) != COUNTS["edges"]:
        chk.fail(f"edges {len(edges)} != {COUNTS['edges']}")
    if len(aos) != COUNTS["aos"]:
        chk.fail(f"assessment objectives {len(aos)} != {COUNTS['aos']}")
    if len(papers) != COUNTS["papers"]:
        chk.fail(f"papers {len(papers)} != {COUNTS['papers']}")
    per_sec = {}
    for p in pts:
        per_sec[int(str(p["official_code"])[0])] = per_sec.get(int(str(p["official_code"])[0]), 0) + 1
    for sec, n in PER_SECTION.items():
        if per_sec.get(sec, 0) != n:
            chk.fail(f"section S{sec} has {per_sec.get(sec, 0)} points != {n}")
    return chk


def check_spec_points(data):
    chk = Check("specification_points")
    pts = data["specification_points.yaml"]["specification_points"]
    codes, gorders = set(), set()
    for i, p in enumerate(pts):
        ctx = f"point[{i}]"
        for k in ("code", "official_code", "official_wording", "section",
                  "subsection", "ordering", "global_order", "c_point",
                  "practical", "applicability", "leading_verb",
                  "draft_skill_tags", "validation_status", "confidence",
                  "version", "provenance", "damage_flags"):
            if k not in p:
                chk.fail(f"{ctx}: missing key '{k}'")
        m = RE_POINT_CODE.match(str(p.get("code", "")))
        if not m:
            chk.fail(f"{ctx}: code '{p.get('code')}' not in 4CH1-* point namespace")
            continue
        code = p["code"]
        if code in codes:
            chk.fail(f"{ctx}: duplicate code {code}")
        codes.add(code)
        if p.get("official_code") != m.group(1):
            chk.fail(f"{ctx}: official_code {p.get('official_code')!r} != {m.group(1)!r}")
        # namespace of structural refs
        if not RE_TOPIC_CODE.match(str(p.get("section", ""))):
            chk.fail(f"{code}: section '{p.get('section')}' not a 4CH1-S[1-4] topic code")
        if not RE_SUBTOPIC_CODE.match(str(p.get("subsection", ""))):
            chk.fail(f"{code}: subsection '{p.get('subsection')}' not a 4CH1-S[1-4]-[a-i] code")
        # c-point semantics
        c = str(p["official_code"]).endswith("C")
        if p.get("c_point") is not c:
            chk.fail(f"{code}: c_point {p.get('c_point')} != suffix semantics {c}")
        app = p.get("applicability", {})
        if not isinstance(app, dict):
            chk.fail(f"{code}: applicability not a mapping")
        else:
            if app.get("double_award_shared") is not False if c else app.get("double_award_shared") is not True:
                chk.fail(f"{code}: double_award_shared inconsistent with C-suffix")
            if app.get("papers") != (["2C"] if c else ["1C", "2C"]):
                chk.fail(f"{code}: applicability.papers {app.get('papers')} wrong for C={c}")
        # ordering
        if not is_int(p.get("ordering")) or p["ordering"] < 1:
            chk.fail(f"{code}: ordering {p.get('ordering')!r} not positive int")
        if not is_int(p.get("global_order")) or p["global_order"] < 1:
            chk.fail(f"{code}: global_order {p.get('global_order')!r} not positive int")
        elif p["global_order"] in gorders:
            chk.fail(f"{code}: duplicate global_order {p['global_order']}")
        gorders.add(p["global_order"])
        # skill tags
        tags = p.get("draft_skill_tags", [])
        if not isinstance(tags, list):
            chk.fail(f"{code}: draft_skill_tags not a list")
        else:
            for t in tags:
                mm = re.match(r"^4CH1-SK-([A-Z]+)$", str(t))
                if not mm or mm.group(1) not in SKILL_TAGS:
                    chk.fail(f"{code}: skill tag '{t}' outside vocabulary")
            if p.get("practical") and "4CH1-SK-PRACTICAL" not in tags:
                chk.fail(f"{code}: practical point lacks 4CH1-SK-PRACTICAL tag")
        # provenance
        prov = p.get("provenance", {})
        check_provenance(chk, prov, code, want_line=True)
        shape = prov.get("row_shape")
        if shape not in ROW_SHAPES:
            chk.fail(f"{code}: row_shape '{shape}' outside vocabulary")
        elif shape == "orphan-line":
            if prov.get("table_index") is not None or prov.get("row_index") is not None:
                chk.fail(f"{code}: orphan-line carries table/row indices")
        else:
            if not is_int(prov.get("table_index")) or not is_int(prov.get("row_index")):
                chk.fail(f"{code}: table_index/row_index missing for in-table row")
        xc = prov.get("pdf_crosscheck", {})
        if not isinstance(xc, dict):
            chk.fail(f"{code}: pdf_crosscheck not a mapping")
        else:
            if xc.get("file") != SOURCE_PDF:
                chk.fail(f"{code}: pdf_crosscheck.file != {SOURCE_PDF}")
            if not is_int(xc.get("page")) or xc.get("page", 0) < 1:
                chk.fail(f"{code}: pdf_crosscheck.page missing/not positive: {xc.get('page')!r}")
            if xc.get("match") not in MATCH_LEVELS:
                chk.fail(f"{code}: pdf_crosscheck.match '{xc.get('match')}' outside vocabulary")
            elif xc.get("match") in ("mismatch", "pdf-missing"):
                chk.fail(f"{code}: PDF cross-check match '{xc.get('match')}' — gate regression")
        # wording: verbatim + foreign scan (4SD0 allowed in applicability.rule only)
        if not isinstance(p.get("official_wording"), str) or not p["official_wording"].strip():
            chk.fail(f"{code}: official_wording empty")
        else:
            scan_foreign(chk, p["official_wording"], code)
        check_base_record(chk, p, code)
    if len(pts) != COUNTS["spec_points"]:
        chk.fail(f"point count {len(pts)} != {COUNTS['spec_points']}")
    if gorders and sorted(gorders) != list(range(1, len(pts) + 1)):
        chk.fail("global_order values are not exactly 1..N")
    return chk, codes


def check_topics(data, point_codes):
    chk = Check("topics")
    d = data["topics.yaml"]
    tops = d["topics"]
    subs = d["subtopics"]
    topic_codes = set()
    for i, t in enumerate(tops):
        ctx = f"topic[{i}]"
        if not RE_TOPIC_CODE.match(str(t.get("code", ""))):
            chk.fail(f"{ctx}: code '{t.get('code')}' not in 4CH1-S[1-4] namespace")
        else:
            sec = int(t["code"][-1])
            if t.get("title") != SECTION_TITLES.get(sec):
                chk.fail(f"{ctx}: title {t.get('title')!r} != canonical section title")
            if t.get("ordering") != sec:
                chk.fail(f"{ctx}: ordering {t.get('ordering')} != section number {sec}")
            topic_codes.add(t["code"])
        check_provenance(chk, t.get("provenance", {}), t.get("code", ctx), want_line=True)
        check_base_record(chk, t, t.get("code", ctx))
    if len(tops) != COUNTS["topics"]:
        chk.fail(f"topic count {len(tops)} != {COUNTS['topics']}")

    sub_codes = set()
    sub_members = {}
    for i, s in enumerate(subs):
        code = str(s.get("code", ""))
        ctx = f"subtopic[{i}] {code}"
        if not RE_SUBTOPIC_CODE.match(code):
            chk.fail(f"{ctx}: not in 4CH1-S[1-4]-[a-i] namespace")
            continue
        if code in sub_codes:
            chk.fail(f"{ctx}: duplicate subtopic code")
        sub_codes.add(code)
        if s.get("parent") != f"4CH1-S{code[-3]}":
            chk.fail(f"{ctx}: parent {s.get('parent')!r} inconsistent with code")
        if s.get("letter") != code[-1]:
            chk.fail(f"{ctx}: letter {s.get('letter')!r} != {code[-1]!r}")
        if s.get("header_source") not in HEADER_SOURCES:
            chk.fail(f"{ctx}: header_source '{s.get('header_source')}' outside vocabulary")
        if not isinstance(s.get("title"), str) or not s["title"].strip():
            chk.fail(f"{ctx}: PDF title missing")
        else:
            scan_foreign(chk, s["title"], ctx)
        members = s.get("spec_points", [])
        if not isinstance(members, list) or not members:
            chk.fail(f"{ctx}: spec_points list missing/empty")
            continue
        for ref in members:
            if ref not in point_codes:
                chk.fail(f"{ctx}: spec_points ref '{ref}' is not a declared spec point")
        if len(members) != len(set(members)):
            chk.fail(f"{ctx}: duplicate refs in spec_points")
        sub_members[code] = members
        if not is_int(s.get("ordering")) or s["ordering"] < 1:
            chk.fail(f"{ctx}: ordering not positive int")
        prov = s.get("provenance", {})
        check_provenance(chk, prov, code)
        if not is_int(prov.get("pdf_header_page")) or prov.get("pdf_header_page", 0) < 1:
            chk.fail(f"{ctx}: provenance pdf_header_page missing/not positive")
        if s.get("header_source") == "md-table" and not is_int(prov.get("md_line")):
            chk.fail(f"{ctx}: md-table header lacks provenance md_line")
        check_base_record(chk, s, ctx)

    # membership equivalence with the points' own declarations
    declared = {}
    for p in data["specification_points.yaml"]["specification_points"]:
        declared.setdefault(str(p.get("subsection")), []).append(p["code"])
    if sub_codes != set(declared):
        chk.fail(f"subtopic code set != subsections declared by points: "
                 f"only-in-subtopics={sorted(sub_codes - set(declared))} "
                 f"only-in-points={sorted(set(declared) - sub_codes)}")
    for code, members in sub_members.items():
        if sorted(members) != sorted(declared.get(code, [])):
            chk.fail(f"{code}: spec_points membership != points' declared subsection")
    # per-subsection ordering contiguity (1..n)
    pts = {p["code"]: p for p in data["specification_points.yaml"]["specification_points"]}
    for code, members in sub_members.items():
        orders = sorted(pts[m]["ordering"] for m in members if m in pts)
        if orders != list(range(1, len(orders) + 1)):
            chk.fail(f"{code}: per-subsection ordering not contiguous 1..n: {orders}")
    if len(subs) != COUNTS["subtopics"]:
        chk.fail(f"subtopic count {len(subs)} != {COUNTS['subtopics']}")
    return chk, topic_codes, sub_codes, sub_members


def check_relationships(data, point_codes, topic_codes, sub_codes, sub_members):
    chk = Check("relationships")
    edges = data["relationships.yaml"]["edges"]
    nodes = point_codes | topic_codes | sub_codes
    seen = set()
    sub_to_topic, point_to_sub = {}, {}
    for i, e in enumerate(edges):
        ctx = f"edge[{i}]"
        fr, rel, to = e.get("from"), e.get("relation"), e.get("to")
        if rel not in LIVE_EDGE_ENUM:
            chk.fail(f"{ctx}: relation '{rel}' not in live V2 knowledge_edges enum")
        if fr not in nodes:
            chk.fail(f"{ctx}: 'from' {fr!r} does not resolve to a declared node")
        if to not in nodes:
            chk.fail(f"{ctx}: 'to' {to!r} does not resolve to a declared node")
        key = (fr, rel, to)
        if key in seen:
            chk.fail(f"{ctx}: duplicate edge {key}")
        seen.add(key)
        if rel == "PART_OF":
            if fr in sub_codes:
                if to not in topic_codes:
                    chk.fail(f"{ctx}: subtopic PART_OF target {to!r} is not a topic")
                sub_to_topic[fr] = to
            elif fr in point_codes:
                if to not in sub_codes:
                    chk.fail(f"{ctx}: spec point PART_OF target {to!r} is not a subtopic")
                point_to_sub[fr] = to
            else:
                chk.fail(f"{ctx}: unexpected PART_OF source {fr!r}")
        if not is_int(e.get("order")) or e["order"] < 1:
            chk.fail(f"{ctx}: order not positive int")
        check_provenance(chk, e.get("provenance", {}), f"edge {fr}->{to}")
        check_base_record(chk, e, ctx)
    # exact coverage
    if sub_to_topic.keys() != sub_codes:
        chk.fail(f"PART_OF subtopic->topic coverage incomplete: missing "
                 f"{sorted(sub_codes - set(sub_to_topic))}")
    if point_to_sub.keys() != point_codes:
        missing = sorted(point_codes - set(point_to_sub))
        chk.fail(f"PART_OF point->subtopic coverage incomplete: {len(missing)} missing "
                 f"(first: {missing[:5]})")
    # agreement with declared structure
    pts = {p["code"]: p for p in data["specification_points.yaml"]["specification_points"]}
    for pc, sub in point_to_sub.items():
        if pts[pc].get("subsection") != sub:
            chk.fail(f"{pc}: edge target {sub} != declared subsection {pts[pc].get('subsection')}")
    subs = {s["code"]: s for s in data["topics.yaml"]["subtopics"]}
    for sc, tc in sub_to_topic.items():
        if subs[sc].get("parent") != tc:
            chk.fail(f"{sc}: edge target {tc} != declared parent {subs[sc].get('parent')}")
    # order fields follow the source structures
    for sc, members in sub_members.items():
        expected = {m: pts[m]["global_order"] for m in members}
        for e in edges:
            if e.get("from") in expected:
                if e.get("order") != expected[e["from"]]:
                    chk.fail(f"edge {e['from']}: order {e.get('order')} != global_order "
                             f"{expected[e['from']]}")
    return chk


def check_command_words(data):
    chk = Check("command_words")
    cws = data["command_words.yaml"]["command_words"]
    seen = set()
    for i, cw in enumerate(cws):
        ctx = f"cw[{i}]"
        code = str(cw.get("code", ""))
        if not RE_CW_CODE.match(code):
            chk.fail(f"{ctx}: code '{code}' not in 4CH1-CW-* namespace")
        if code in seen:
            chk.fail(f"{ctx}: duplicate code {code}")
        seen.add(code)
        if not isinstance(cw.get("command_word"), str) or not cw["command_word"].strip():
            chk.fail(f"{ctx}: command_word empty")
        if cw.get("category") not in CW_CATEGORIES:
            chk.fail(f"{ctx}: category '{cw.get('category')}' outside vocabulary")
        if not isinstance(cw.get("definition"), str) or not cw["definition"].strip():
            chk.fail(f"{ctx}: definition empty")
        else:
            scan_foreign(chk, cw["definition"], code)
        if cw.get("ordering") != i + 1:
            chk.fail(f"{ctx}: ordering {cw.get('ordering')} != position {i + 1}")
        prov = cw.get("provenance", {})
        check_provenance(chk, prov, code, want_line=True)
        if not is_int(prov.get("table_index")) or not is_int(prov.get("row_index")):
            chk.fail(f"{code}: provenance table_index/row_index missing")
        check_base_record(chk, cw, code)
    if len(cws) != COUNTS["command_words"]:
        chk.fail(f"command-word count {len(cws)} != {COUNTS['command_words']}")
    return chk


def check_practicals(data, point_codes):
    chk = Check("practicals")
    prs = data["practicals.yaml"]["practicals"]
    pts = {p["code"]: p for p in data["specification_points.yaml"]["specification_points"]}
    flagged = {p["code"] for p in pts.values() if p.get("practical")}
    covered = set()
    for i, pr in enumerate(prs):
        ctx = f"practical[{i}]"
        code = str(pr.get("code", ""))
        if not RE_PR_CODE.match(code):
            chk.fail(f"{ctx}: code '{code}' not in 4CH1-PR-## namespace")
        if pr.get("ordering") != i + 1:
            chk.fail(f"{ctx}: ordering {pr.get('ordering')} != position {i + 1}")
        sp = pr.get("spec_point")
        if sp not in point_codes:
            chk.fail(f"{ctx}: spec_point {sp!r} not a declared spec point")
        else:
            if sp not in flagged:
                chk.fail(f"{ctx}: spec_point {sp} is not practical-flagged")
            if sp in covered:
                chk.fail(f"{ctx}: spec_point {sp} covered twice")
            covered.add(sp)
            if pr.get("subsection") != pts[sp].get("subsection"):
                chk.fail(f"{ctx}: subsection {pr.get('subsection')!r} != point's "
                         f"{pts[sp].get('subsection')!r}")
        if not isinstance(pr.get("summary"), str) or not pr["summary"].strip():
            chk.fail(f"{ctx}: summary empty")
        prov = pr.get("provenance", {})
        check_provenance(chk, prov, code, want_line=True)
        check_base_record(chk, pr, code)
    if covered != flagged:
        chk.fail(f"practical coverage != practical-flagged points: missing "
                 f"{sorted(flagged - covered)}")
    if len(prs) != COUNTS["practicals"]:
        chk.fail(f"practical count {len(prs)} != {COUNTS['practicals']}")
    return chk


def check_assessment(data):
    chk = Check("assessment_objectives")
    d = data["assessment_objectives.yaml"]
    aos = d["assessment_objectives"]
    papers = d["papers"]
    for i, ao in enumerate(aos):
        code = str(ao.get("code", ""))
        if not RE_AO_CODE.match(code):
            chk.fail(f"ao[{i}]: code '{code}' not in 4CH1-AO[1-3] namespace")
        if not isinstance(ao.get("title"), str) or not ao["title"].strip():
            chk.fail(f"{code}: title empty")
        if not isinstance(ao.get("weighting_overall"), str):
            chk.fail(f"{code}: weighting_overall missing")
        wbp = ao.get("weighting_by_paper")
        if not isinstance(wbp, dict) or set(wbp) != {"paper_1", "paper_2"}:
            chk.fail(f"{code}: weighting_by_paper keys != paper_1/paper_2")
        else:
            for pk, pv in wbp.items():
                if not isinstance(pv, dict) or set(pv) != {"ao1", "ao2", "ao3"}:
                    chk.fail(f"{code}: weighting_by_paper.{pk} keys != ao1/ao2/ao3")
        check_provenance(chk, ao.get("provenance", {}), code)
        check_base_record(chk, ao, code)
    if len(aos) != COUNTS["aos"]:
        chk.fail(f"AO count {len(aos)} != {COUNTS['aos']}")

    seen = set()
    expected_codes = {"4CH1-P1C", "4CH1-P2C"}
    for i, p in enumerate(papers):
        ctx = f"paper[{i}]"
        code = str(p.get("code", ""))
        if not RE_PAPER_CODE.match(code):
            chk.fail(f"{ctx}: code '{code}' not in 4CH1-P[12]C namespace")
        if code in seen:
            chk.fail(f"{ctx}: duplicate paper code {code}")
        seen.add(code)
        if p.get("paper_code") not in ("4CH1/1C", "4CH1/2C"):
            chk.fail(f"{ctx}: paper_code {p.get('paper_code')!r} not a 4CH1 paper code")
        for k in ("marks", "duration_minutes"):
            if not is_int(p.get(k)) or p[k] < 1:
                chk.fail(f"{ctx}: {k} {p.get(k)!r} not a positive int")
        if not isinstance(p.get("weighting"), str) or not p["weighting"].endswith("%"):
            chk.fail(f"{ctx}: weighting {p.get('weighting')!r} not a percentage")
        if not isinstance(p.get("content_rule"), str) or not p["content_rule"].strip():
            chk.fail(f"{ctx}: content_rule empty")
        else:
            scan_foreign(chk, p["content_rule"], code)
        check_provenance(chk, p.get("provenance", {}), code, want_line=True)
        check_base_record(chk, p, code)
    if seen != expected_codes:
        chk.fail(f"paper codes {sorted(seen)} != {sorted(expected_codes)}")
    return chk


def check_namespace_prose(data):
    """4SD0 may appear ONLY in the applicability rule prose (Double Award)."""
    chk = Check("namespace_prose")
    pts = data["specification_points.yaml"]["specification_points"]
    for p in pts:
        rule = p.get("applicability", {}).get("rule", "")
        if isinstance(rule, str) and RE_4SD0_ANY.search(rule) and "Double Award" not in rule:
            chk.fail(f"{p['code']}: 4SD0 mentioned outside the Double-Award rule")
    return chk


def check_notes_mapping(data, point_codes, sub_codes, notes_root=None):
    """Check group 6 — T-C10 note->spec-point mapping state (front matter)."""
    chk = Check("c10-notes-mapping")
    notes_root = Path(notes_root) if notes_root else NOTES_ROOT_DEFAULT

    note_files = sorted(p for p in notes_root.rglob("*.md")
                        if "assets" not in p.parts)
    if len(note_files) != C10_COUNTS["notes"]:
        chk.fail(f"note count {len(note_files)} != {C10_COUNTS['notes']}")

    total_maps, covered = 0, set()
    n_notes = 0
    for path in note_files:
        rel = path.relative_to(notes_root.parent)
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        if not lines or lines[0].strip() != "---":
            chk.fail(f"c10.1 no front matter: {rel}")
            continue
        try:
            close = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
            fm = yaml.safe_load("\n".join(lines[1:close])) or {}
        except (StopIteration, yaml.YAMLError):
            chk.fail(f"c10.1 unparseable front matter: {rel}")
            continue
        sm = fm.get("spec_map")
        if not isinstance(sm, dict):
            chk.fail(f"c10.1 missing spec_map: {rel}")
            continue
        n_notes += 1
        # c10.1 schema
        for key in ("curriculum_code", "phase", "subsection", "spec_points",
                    "mapped_date", "mapper"):
            if key not in sm:
                chk.fail(f"c10.1 spec_map missing key {key}: {rel}")
        if sm.get("curriculum_code") != "4CH1-2017":
            chk.fail(f"c10.1 wrong curriculum_code {sm.get('curriculum_code')!r}: {rel}")
        # c10.4 PROVIDER anchor vs slug
        sub = sm.get("subsection")
        if sub not in sub_codes:
            chk.fail(f"c10.4 unknown subsection {sub!r}: {rel}")
        sp = sm.get("subsection_provenance", {})
        for key in ("tier", "signal", "slug", "validation_status"):
            if key not in sp:
                chk.fail(f"c10.4 subsection_provenance missing {key}: {rel}")
        if sp.get("tier") != "PROVIDER" or sp.get("signal") != "source-url-slug":
            chk.fail(f"c10.4 bad subsection provenance tier/signal: {rel}")
        url = fm.get("source") or ""
        parsed = parse_slug(url) if url else None
        if parsed:
            sec, grp, group_slug, _, _ = parsed
            want_sub = f"4CH1-S{sec}-{SECTION_LETTERS[grp - 1]}"
            if sub != want_sub:
                chk.fail(f"c10.4 anchor {sub} != slug-derived {want_sub}: {rel}")
            if sp.get("slug") != group_slug:
                chk.fail(f"c10.4 provenance slug {sp.get('slug')!r} != URL group "
                         f"{group_slug!r}: {rel}")
        # c10.5 mappings present, unique
        sps = sm.get("spec_points") or []
        if not sps:
            chk.fail(f"c10.5 zero mappings: {rel}")
        codes = [m.get("code") for m in sps]
        if len(codes) != len(set(codes)):
            chk.fail(f"c10.5 duplicate codes: {rel}")
        # c10.2 registry + c10.3 provenance completeness
        for m in sps:
            c = m.get("code")
            if c not in point_codes:
                chk.fail(f"c10.2 code not in 182-registry: {c} ({rel})")
            prov = m.get("provenance", {})
            if prov.get("tier") != "AI_SUGGESTED":
                chk.fail(f"c10.3 wrong tier {prov.get('tier')!r} for {c}: {rel}")
            if prov.get("confidence") not in C10_CONFIDENCE:
                chk.fail(f"c10.3 bad confidence {prov.get('confidence')!r} for {c}: {rel}")
            for key in ("model_version", "evidence", "rationale"):
                if not prov.get(key):
                    chk.fail(f"c10.3 missing {key} for {c}: {rel}")
            # validation state: SUGGESTED (clean, no stray promotion fields)
            # or HUMAN_VALIDATED (validated_by + ISO date required; tier must
            # still be AI_SUGGESTED — origin is immutable, checked above)
            vs = prov.get("validation_status")
            if vs == "HUMAN_VALIDATED":
                if not prov.get("validated_by"):
                    chk.fail(f"c10.3 HUMAN_VALIDATED missing validated_by "
                             f"for {c}: {rel}")
                if not re.fullmatch(r"\d{4}-\d{2}-\d{2}",
                                    str(prov.get("validated_date", ""))):
                    chk.fail(f"c10.3 bad validated_date "
                             f"{prov.get('validated_date')!r} for {c}: {rel}")
            elif vs != "SUGGESTED":
                chk.fail(f"c10.3 validation_status {vs!r} "
                         f"for {c}: {rel}")
            else:
                for key in ("validated_by", "validated_date"):
                    if prov.get(key):
                        chk.fail(f"c10.3 stray {key} on SUGGESTED mapping "
                                 f"{c}: {rel}")
            if c in point_codes:
                covered.add(c)
                total_maps += 1
        # c10.6 foreign codes in front matter (Wxx unit codes, 4CH0, IAL)
        fm_text = "\n".join(lines[1:close])
        for m in re.finditer(r"\b(W[A-Z]{2}\d{1,2}|4CH0|IAL|4SC0)\b", fm_text):
            chk.fail(f"c10.6 foreign curriculum code {m.group(1)!r} in front matter: {rel}")

    # c10.7 totals
    if n_notes != C10_COUNTS["notes"]:
        chk.fail(f"c10.7 notes with spec_map {n_notes} != {C10_COUNTS['notes']}")
    if total_maps != C10_COUNTS["mappings"]:
        chk.fail(f"c10.7 total mappings {total_maps} != {C10_COUNTS['mappings']}")
    if len(covered) != C10_COUNTS["points_covered"]:
        chk.fail(f"c10.7 covered points {len(covered)} != "
                 f"{C10_COUNTS['points_covered']}")
    return chk


# --- T-C11 pilot (Phase 3, 2026-09-11) ----------------------------------------
# Concept/prerequisite/misconception graph for the frozen pilot slice
# 1.25-1.36. Contract: graph/reports/C11_ARCHITECTURE.md. Generated by
# scripts/c11_concept_pilot.py from scripts/c11_pilot_decisions.yaml.
C11_FILES = ["concepts.yaml", "concept_edges.yaml", "spec_command_kinds.yaml"]
C11_GENERATOR = "scripts/c11_concept_pilot.py"
# Session-47 (§16 batch 1, 2026-09-12): the store covers the pilot slice PLUS
# the first authorized expansion batch (4CH1-1.1-1.12, decision record
# scripts/c11_batch1_decisions.yaml, extraction_pass c11-s16-batch-1) per the
# §16 authorization (scripts/c11_s16_authorization.yaml). Batch-1 content is
# SUGGESTED until its own operator review gate + §18 promotion.
C11_PILOT_SPS = ["4CH1-1.25", "4CH1-1.26", "4CH1-1.27", "4CH1-1.28",
                 "4CH1-1.29", "4CH1-1.30", "4CH1-1.31", "4CH1-1.32",
                 "4CH1-1.33", "4CH1-1.34C", "4CH1-1.35C", "4CH1-1.36"]
C11_BATCH1_SPS = ["4CH1-1.1", "4CH1-1.2", "4CH1-1.3", "4CH1-1.4", "4CH1-1.5C",
                   "4CH1-1.6C", "4CH1-1.7C", "4CH1-1.8", "4CH1-1.9",
                   "4CH1-1.10", "4CH1-1.11", "4CH1-1.12"]
# session-49: batch-2 slice (paper-chromatography practical + atomic
# structure + the Periodic Table)
C11_BATCH2_SPS = ["4CH1-1.13", "4CH1-1.14", "4CH1-1.15", "4CH1-1.16",
                   "4CH1-1.17", "4CH1-1.18", "4CH1-1.19", "4CH1-1.20",
                   "4CH1-1.21", "4CH1-1.22", "4CH1-1.23", "4CH1-1.24"]
C11_SCOPE_SPS = C11_PILOT_SPS + C11_BATCH1_SPS + C11_BATCH2_SPS
C11_STAGE = "pilot+s16-batch-1+s16-batch-2"
C11_NEGATIVE_CONTROL = "4CH1-4.15"
# State after the session-50 batch-2 verdict application: 67 nodes (29 pilot
# + 24 batch-1 + 14 batch-2), 156 edges (72 PART_OF + 84 semantic), 79
# HUMAN_VALIDATED (28 pilot session-45 + 28 batch-1 session-48 + 23 batch-2
# session-50 — all operator §18 promotions; the only SUGGESTED semantic edges
# left are the 3 pilot operator HOLDs; batch-2 nodes stay SUGGESTED: nodes
# have no §18 pathway), 2 REVIEW_REQUIRED (the frozen pilot RR operator-HOLD
# edge + the settled batch-1 RR quarantine HOLD_REVIEW_REQUIRED; batch 2
# authored no new RR). (Session-49 note: the counts were 56 HV at the batch-2
# authoring gate; session 50 applied the operator's batch-2 verdicts.)
C11_COUNTS = {"nodes": 67, "concepts": 61, "misconceptions": 6, "edges": 156,
              "part_of": 72, "requires_prerequisite": 63, "explained_by": 8,
              "related_to": 0, "commonly_confused_with": 1,
              "misconception_of": 1, "wrong_answer_pattern": 5,
              "remediated_by": 6, "review_required": 2, "command_kinds": 36}
# Post-operator-REJECT state (session 41, 2026-09-11): the operator rejected
# `4CH1-PR-03 REQUIRES_PREREQUISITE 4CH1-CON-MOLE` — it was re-authored out of
# the decision record (preserved as rejected candidate HELD-13; architecture
# §7: REJECTED is not a graph state). 66->65 edges, RP 26->25, RR 2->1.
C11_FAMILIES = {"CONCEPT", "MISCONCEPTION"}
C11_PATTERN_CLASSES = {"ERRONEOUS_BELIEF", "WRONG_ANSWER_PATTERN"}
C11_ROLES = {"CORE", "SUPPORTING", "ENRICHMENT"}
C11_RELATIONS = {"PART_OF", "REQUIRES_PREREQUISITE", "RELATED_TO",
                 "MISCONCEPTION_OF", "EXPLAINED_BY", "REMEDIATED_BY",
                 "COMMONLY_CONFUSED_WITH", "WRONG_ANSWER_PATTERN"}
C11_MISCONCEPTION_RELATIONS = {"MISCONCEPTION_OF", "WRONG_ANSWER_PATTERN",
                               "REMEDIATED_BY"}
C11_ANCHOR_KINDS = {"NOTE", "SPEC", "MARK_SCHEME"}
C11_STATES = {"SUGGESTED", "REVIEW_REQUIRED"}
C11_EDGE_STATES = {"SUGGESTED", "REVIEW_REQUIRED", "HUMAN_VALIDATED"}
C11_PROMOTIONS_FILE = REPO / "scripts" / "c11_promotions.yaml"
# Session-47: the decision-record REGISTRY (pilot + each authorized §16 batch
# record). The generator's registry and this list must stay in lockstep.
C11_DECISIONS_FILES = [REPO / "scripts" / "c11_pilot_decisions.yaml",
                       REPO / "scripts" / "c11_batch1_decisions.yaml",
                       REPO / "scripts" / "c11_batch2_decisions.yaml"]
C11_DECISIONS_FILE = C11_DECISIONS_FILES[0]
_C11_AI_NAME_RE = re.compile(r"glm|super\s*z|gpt|claude|openai|anthropic|\bai\b"
                             r"|llm|agent|model|bot", re.I)
C11_BANDS = {"high", "medium", "low"}
C11_DERIVATION_CAPS = {
    "SPEC_VERBATIM": "high", "DEFINITIONAL_DEPENDENCY": "high",
    "USED_WITHOUT_RETEACHING": "high", "EXPLICIT_TEACH_SEQUENCE": "high",
    "SINGLE_SOURCE_CAUSAL_TEACHING": "high", "ASSESSMENT_DOCUMENTED": "high",
    "EXAMINER_TIP_EXPLICIT": "high", "TEACH_SEQUENCE_WITHIN_NOTE": "medium",
    "IMPLICIT_USE": "medium", "EXAMINER_TIP_IMPLIED": "low",
    "RELATED_RESIDUAL": "medium"}
C11_GUIDE_CLASSES = {"KNOW_TERM", "EXPLAIN_HOW", "CALCULATE", "DESCRIBE_EXPERIMENT",
                     "REPRESENT_DIAGRAM", "UNDERSTAND_RELATION", "PRODUCE_EQUATION"}
RE_C11_NODE = re.compile(r"^4CH1-(CON|MIS)-[A-Z0-9-]+$")

# T-C10 norm() convention (anti-hallucination quote normalisation, shared with
# c10_map_notes.py and c11_concept_pilot.py — see those files for the source).
_C11_TRANS = {ord("–"): "-", ord("—"): "-", ord("″"): '"', ord("′"): "'"}


def c11_norm(s):
    s = unicodedata.normalize("NFC", s)
    s = s.replace("\\", "")
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", s)
    s = re.sub(r"<[^>]+>", "", s)
    s = re.sub(r"[*_`#>]+", "", s)
    s = s.translate(_C11_TRANS)
    s = re.sub(r"\s+", " ", s)
    return s.strip()


def load_c11(graph_dir):
    data = {}
    for fn in C11_FILES:
        p = graph_dir / fn
        if not p.exists():
            print(f"FATAL: missing {p}", file=sys.stderr)
            sys.exit(1)
        try:
            data[fn] = yaml.safe_load(p.read_text(encoding="utf-8"))
        except yaml.YAMLError as e:
            print(f"FATAL: {fn} does not parse: {e}", file=sys.stderr)
            sys.exit(1)
        if not isinstance(data[fn], dict) or "meta" not in data[fn]:
            print(f"FATAL: {fn} is not a mapping with a 'meta' key",
                  file=sys.stderr)
            sys.exit(1)
    return data


_C11_TC10_INDEX = None
_C11_PROMO_STATE = None


def c11_promotion_state():
    """Operator-side promotion state, read from the REAL repo files (the
    negative-test graph copies cannot cheat them, same guarantee as the
    T-C10 notes crosscheck). Returns (promo_entries, problems, authored):
      promo_entries: {(src, rel, tgt): entry} from scripts/c11_promotions.yaml
      problems:      c11.13 failures (schema/anti-forgery/resolution)
      authored:      {(src, rel, tgt): validation_status} merged across
                     the decision-record registry (drift detection vs the
                     generated graph)
    """
    global _C11_PROMO_STATE
    if _C11_PROMO_STATE is not None:
        return _C11_PROMO_STATE
    problems, entries, authored = [], {}, {}
    dec = {"held": []}

    # decision-record REGISTRY (session-47: pilot + each authorized §16 batch
    # record): authored-edge identities + statuses + anti-forgery + held
    # candidates, MERGED across records
    for dec_file in C11_DECISIONS_FILES:
        if not dec_file.exists():
            problems.append(f"c11.13 decision record missing: {dec_file}")
            continue
        try:
            d = yaml.safe_load(dec_file.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError as e:
            problems.append(f"c11.13 decision record does not parse: "
                            f"{dec_file}: {e}")
            continue
        for e in d.get("edges", []):
            key = (e.get("source"), e.get("relation"), e.get("target"))
            if key in authored:
                problems.append(f"c11.13 registry: edge identity {key} "
                                f"duplicated across decision records")
                continue
            authored[key] = e.get("validation_status")
            if e.get("validation_status") == "HUMAN_VALIDATED":
                problems.append(
                    f"c11.13 decision record carries HUMAN_VALIDATED on "
                    f"{key[0]} {key[1]} {key[2]} — the AI decision record may "
                    f"never carry it (anti-forgery; promotion is operator-only "
                    f"via scripts/c11_promotions.yaml)")
        for n in d.get("nodes", []):
            if n.get("validation_status") == "HUMAN_VALIDATED":
                problems.append(
                    f"c11.13 decision record carries HUMAN_VALIDATED on node "
                    f"{n.get('code')} — anti-forgery (node promotion pathway "
                    f"not built; nodes are SUGGESTED/REVIEW_REQUIRED only)")
        dec.setdefault("held", []).extend(d.get("held") or [])

    # promotions file: schema + attribution + resolution
    if C11_PROMOTIONS_FILE.exists():
        try:
            data = yaml.safe_load(C11_PROMOTIONS_FILE.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError as e:
            data = {}
            problems.append(f"c11.13 promotions file does not parse: {e}")
        for i, p in enumerate(data.get("promotions") or []):
            where = f"c11.13 promotion[{i}]"
            if not isinstance(p, dict):
                problems.append(f"{where}: entry must be a mapping")
                continue
            edge = p.get("edge")
            if not isinstance(edge, dict):
                problems.append(f"{where}: 'edge' must be a mapping "
                                f"{{source, relation, target}}")
                continue
            src, rel, tgt = edge.get("source"), edge.get("relation"), \
                edge.get("target")
            if not all(isinstance(x, str) and x.strip() for x in (src, rel, tgt)):
                problems.append(f"{where}: exact identity missing/empty — "
                                f"promotion by node or relation type alone is "
                                f"forbidden")
                continue
            key = (src, rel, tgt)
            if rel not in C11_RELATIONS:
                problems.append(f"{where}: unknown relation {rel!r}")
                continue
            if rel == "PART_OF":
                problems.append(f"{where}: PART_OF is derived — not promotable "
                                f"via this pathway")
                continue
            if key in entries:
                problems.append(f"{where}: duplicate promotion for "
                                f"{src} {rel} {tgt}")
                continue
            by, dt = p.get("validated_by"), p.get("validated_date")
            if not isinstance(by, str) or not by.strip():
                problems.append(f"{where}: validated_by missing — promotion is "
                                f"operator-only")
            elif _C11_AI_NAME_RE.search(by):
                problems.append(f"{where}: validated_by {by!r} fails the "
                                f"attribution gate — AI cannot promote")
            if not isinstance(dt, str) or not re.match(r"^\d{4}-\d{2}-\d{2}$",
                                                       dt or ""):
                problems.append(f"{where}: validated_date must be "
                                f"YYYY-MM-DD, got {dt!r}")
            ref = p.get("review_reference")
            if not isinstance(ref, str) or not ref.strip():
                problems.append(f"{where}: review_reference must name the "
                                f"ratifying review artifact")
            else:
                first = ref.split()[0]
                if first.endswith((".md", ".json", ".yaml")) \
                        and not (REPO / first).exists():
                    problems.append(f"{where}: review_reference file not "
                                    f"found: {first}")
            if key not in authored:
                # held-candidate texts use the compact no-prefix form
                s_, t_ = src.removeprefix("4CH1-"), tgt.removeprefix("4CH1-")
                hit = next((h.get("id") for h in dec.get("held", [])
                            if s_ in str(h.get("candidate", ""))
                            and t_ in str(h.get("candidate", ""))
                            and rel in str(h.get("candidate", ""))), None)
                if hit:
                    problems.append(f"{where}: {src} {rel} {tgt} is held "
                                    f"candidate {hit} — held/rejected "
                                    f"candidates are not promotable")
                else:
                    problems.append(f"{where}: no authored edge matches the "
                                    f"exact identity {src} {rel} {tgt} — "
                                    f"promotion operates on existing "
                                    f"authored-edge identities only")
                continue
            entries[key] = p

    _C11_PROMO_STATE = (entries, problems, authored)
    return _C11_PROMO_STATE


def tc10_index():
    """note rel-path -> {SP codes with HUMAN_VALIDATED T-C10 mapping}."""
    global _C11_TC10_INDEX
    if _C11_TC10_INDEX is None:
        idx = {}
        for path in NOTES_ROOT_DEFAULT.rglob("*.md"):
            if "assets" in path.parts:
                continue
            try:
                text = path.read_text(encoding="utf-8")
                m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
                if not m:
                    continue
                fm = yaml.safe_load(m.group(1)) or {}
                for sp in (fm.get("spec_map") or {}).get("spec_points", []):
                    if (sp.get("provenance") or {}).get("validation_status") \
                            == "HUMAN_VALIDATED":
                        idx.setdefault(str(path.relative_to(REPO)), set()).add(
                            sp.get("code"))
            except (yaml.YAMLError, OSError):
                continue
        _C11_TC10_INDEX = idx
    return _C11_TC10_INDEX


def check_c11_concepts(c11, c09_data):
    """Check group 10 — T-C11 pilot concept nodes + command-kind tags."""
    chk = Check("c11-concepts")
    d = c11["concepts.yaml"]
    meta = d["meta"]
    sps = {sp["code"]: sp for sp in c09_data["specification_points.yaml"]
           ["specification_points"]}
    idx = tc10_index()

    def meta_checks(m, kind):
        for k in ("task", "stage", "curriculum_code", "phase", "scope",
                  "spec_points", "practicals", "negative_control", "generator",
                  "decision_record", "extraction_pass", "model_version",
                  "contract", "generated", "provenance_default",
                  "validation_gate", "edge_vocabulary", "counts"):
            if k not in m:
                chk.fail(f"c11.1 {kind}: meta missing {k!r}")
        # session-47: merged store (pilot + §16 batch 1); stage is the
        # registry-joined value emitted by the generator
        if m.get("task") != "T-C11" or m.get("stage") != C11_STAGE:
            chk.fail(f"c11.1 {kind}: not the T-C11 {C11_STAGE} store")
        if m.get("curriculum_code") != "4CH1-2017" or m.get("phase") != 3:
            chk.fail(f"c11.1 {kind}: curriculum/phase wrong")
        if m.get("generator") != C11_GENERATOR:
            chk.fail(f"c11.1 {kind}: generator {m.get('generator')!r}")
        if m.get("negative_control") != C11_NEGATIVE_CONTROL:
            chk.fail(f"c11.1 {kind}: negative_control must be 4CH1-4.15")
        if sorted(m.get("spec_points") or []) != sorted(C11_SCOPE_SPS):
            chk.fail(f"c11.1 {kind}: meta.spec_points != the 24 registry SPs "
                     f"(pilot + batch 1)")
        if m.get("provenance_default") != "AI_SUGGESTED":
            chk.fail(f"c11.1 {kind}: provenance_default must be AI_SUGGESTED")

    meta_checks(meta, "concepts")
    nodes = d["nodes"]
    if len(nodes) != C11_COUNTS["nodes"]:
        chk.fail(f"c11.2 nodes {len(nodes)} != {C11_COUNTS['nodes']}")
    if sum(1 for n in nodes if n.get("family") == "CONCEPT") \
            != C11_COUNTS["concepts"]:
        chk.fail("c11.2 concept count mismatch")
    if sum(1 for n in nodes if n.get("family") == "MISCONCEPTION") \
            != C11_COUNTS["misconceptions"]:
        chk.fail("c11.2 misconception count mismatch")
    if (meta.get("counts") or {}).get("nodes") != len(nodes):
        chk.fail("c11.1 concepts meta.counts.nodes != actual")

    seen = set()
    for n in nodes:
        code = n.get("code")
        where = f"node {code}"
        if not RE_C11_NODE.match(str(code)):
            chk.fail(f"c11.1 {where}: code not in 4CH1-(CON|MIS)-* namespace")
        if code in seen:
            chk.fail(f"c11.1 {where}: duplicate node code")
        seen.add(code)
        if n.get("family") not in C11_FAMILIES:
            chk.fail(f"c11.1 {where}: family {n.get('family')!r}")
        if n.get("validation_status") not in C11_STATES:
            chk.fail(f"c11.10 {where}: validation_status "
                     f"{n.get('validation_status')!r} (generation may emit "
                     f"SUGGESTED/REVIEW_REQUIRED only — HUMAN_VALIDATED is "
                     f"operator-only, promotion pathway not yet built)")
        if n.get("confidence") not in C11_BANDS:
            chk.fail(f"c11.1 {where}: confidence {n.get('confidence')!r}")
        # c11.14 dual-track alias discipline (operator alias policy
        # RETRIEVAL_EXEMPT, session 44, applied session 45): a term may sit on
        # exactly one track — aliases (corpus-evidenced / merge input) or
        # retrieval_only_aliases (marked unevidenced) — never both.
        ro = n.get("retrieval_only_aliases")
        if ro is not None:
            if not isinstance(ro, list) or not all(
                    isinstance(a, str) and a.strip() for a in ro):
                chk.fail(f"c11.14 {where}: retrieval_only_aliases must be a "
                         f"list of non-empty strings")
            overlap = {str(a).casefold() for a in ro} \
                & {str(a).casefold() for a in (n.get("aliases") or [])}
            if overlap:
                chk.fail(f"c11.14 {where}: dual-track violation — "
                         f"{sorted(overlap)} on BOTH alias tracks")
        prov = n.get("provenance") or {}
        for k in ("tier", "model_version", "extraction_pass", "derivation_method",
                  "derivation_notes", "upstream", "generated_date"):
            if not prov.get(k):
                chk.fail(f"c11.3 {where}: provenance.{k} missing")
        if prov.get("tier") != "AI_SUGGESTED":
            chk.fail(f"c11.3 {where}: tier must be AI_SUGGESTED")
        if prov.get("derivation_method") not in C11_DERIVATION_CAPS:
            chk.fail(f"c11.3 {where}: derivation_method not in vocabulary")
        else:
            cap = C11_DERIVATION_CAPS[prov["derivation_method"]]
            rank = {"low": 0, "medium": 1, "high": 2}
            if rank[n["confidence"]] > rank[cap]:
                chk.fail(f"c11.9 {where}: confidence {n['confidence']!r} "
                         f"exceeds cap {cap!r}")
        if n.get("family") == "MISCONCEPTION":
            if n.get("pattern_class") not in C11_PATTERN_CLASSES:
                chk.fail(f"c11.1 {where}: pattern_class required")
            if not (n.get("evidence")):
                chk.fail(f"c11.11 {where}: misconception without source-quoted "
                         f"evidence")
            if not (n.get("remediation_evidence")):
                chk.fail(f"c11.11 {where}: misconception without remediation "
                         f"evidence")
            for a in (n.get("evidence") or []) + (n.get("remediation_evidence")
                                                   or []):
                _c11_anchor_check(chk, a, where, idx, sps)
        else:
            for att in n.get("spec_points") or []:
                aw = f"{where} @ {att.get('code')}"
                if att.get("code") == C11_NEGATIVE_CONTROL:
                    chk.fail(f"c11.5 {aw}: NEGATIVE CONTROL — no node may "
                             f"attach to 4CH1-4.15")
                elif att.get("code") not in C11_SCOPE_SPS:
                    chk.fail(f"c11.5 {aw}: outside the decision-record "
                             f"registry scope (pilot + batch 1)")
                if att.get("role") not in C11_ROLES:
                    chk.fail(f"c11.1 {aw}: role {att.get('role')!r}")
                _c11_attachment_check(chk, att, aw, idx, sps)

    # command kinds
    ck = c11["spec_command_kinds.yaml"]
    meta_checks(ck["meta"], "command_kinds")
    cks = ck["command_kinds"]
    if len(cks) != C11_COUNTS["command_kinds"]:
        chk.fail(f"c11.12 {len(cks)} command-kind tags != "
                 f"{C11_COUNTS['command_kinds']}")
    if sorted(c.get("code") for c in cks) != sorted(C11_SCOPE_SPS):
        chk.fail("c11.12 command-kind codes != the pilot + batch-1 SPs")
    for c in cks:
        where = f"command_kind {c.get('code')}"
        if c.get("guide_class") not in C11_GUIDE_CLASSES:
            chk.fail(f"c11.12 {where}: guide_class {c.get('guide_class')!r}")
        if c.get("verb") != sps.get(c.get("code"), {}).get("leading_verb"):
            chk.fail(f"c11.12 {where}: verb != registry leading_verb")
        for k in ("verb", "guide_class", "demanded_substance"):
            if not c.get(k):
                chk.fail(f"c11.12 {where}: missing {k!r}")
    return chk


def _c11_anchor_check(chk, a, where, idx, sps):
    if not isinstance(a, dict) or a.get("kind") not in C11_ANCHOR_KINDS:
        chk.fail(f"c11.1 {where}: bad anchor {a!r}")
        return
    rel, quote = a.get("file"), a.get("quote")
    if not rel or not quote:
        chk.fail(f"c11.1 {where}: anchor missing file/quote")
        return
    p = REPO / rel
    if not p.exists():
        chk.fail(f"c11.4 {where}: anchor file missing: {rel}")
        return
    if a["kind"] == "NOTE" and "Chemistry IGCSE Revision Notes" not in rel:
        chk.fail(f"c11.1 {where}: NOTE anchor outside the notes corpus: {rel}")
    if a["kind"] == "SPEC" and rel != "graph/specification_points.yaml":
        chk.fail(f"c11.1 {where}: SPEC anchor must be "
                 f"graph/specification_points.yaml: {rel}")
    if a["kind"] == "MARK_SCHEME" and not rel.startswith("scripts/c11_evidence/"):
        chk.fail(f"c11.1 {where}: MARK_SCHEME anchor outside the pinned "
                 f"extractions: {rel}")
    if c11_norm(quote) not in c11_norm(p.read_text(encoding="utf-8")):
        chk.fail(f"c11.4 {where}: quote NOT found in {rel} :: {quote[:60]!r}")


def _c11_attachment_check(chk, att, where, idx, sps):
    ok = False
    for a in att.get("evidence") or []:
        _c11_anchor_check(chk, a, where, idx, sps)
        kind, rel, quote = a.get("kind"), a.get("file"), a.get("quote")
        if kind == "SPEC":
            sp = sps.get(att.get("code"))
            if sp and c11_norm(quote) in c11_norm(sp["official_wording"]):
                ok = True
        elif kind == "NOTE":
            if att.get("code") in idx.get(rel, set()):
                ok = True
    if not ok:
        chk.fail(f"c11.6 {where}: no anchor resolves to the SP (SPEC quote "
                 f"inside its official wording, or a NOTE whose T-C10 mapping "
                 f"to this SP is HUMAN_VALIDATED)")


def check_c11_concept_edges(c11, c09_data):
    """Check group 11 — T-C11 pilot concept edges (derived PART_OF + authored)."""
    chk = Check("c11-concept-edges")
    d = c11["concept_edges.yaml"]
    meta = d["meta"]
    sps = {sp["code"]: sp for sp in c09_data["specification_points.yaml"]
           ["specification_points"]}
    prs = {p["code"]: p for p in c09_data["practicals.yaml"]["practicals"]}
    idx = tc10_index()
    nodes = {n["code"]: n for n in c11["concepts.yaml"]["nodes"]}
    # §18 promotion crosscheck state — always read from the REAL repo files
    # (promotions record + frozen decision record), corruption-proof for the
    # negative-test graph copies
    promo_entries, promo_problems, authored_states = c11_promotion_state()
    for msg in promo_problems:
        chk.fail(msg)

    for k in ("counts",):
        if k not in meta:
            chk.fail(f"c11.1 edges: meta missing {k!r}")
    edges = d["edges"]
    counts = meta.get("counts") or {}
    if counts.get("edges") != len(edges):
        chk.fail(f"c11.1 edges: meta.counts.edges {counts.get('edges')} "
                 f"!= actual {len(edges)}")
    if len(edges) != C11_COUNTS["edges"]:
        chk.fail(f"c11.2 edges {len(edges)} != {C11_COUNTS['edges']}")
    by_rel = {}
    for e in edges:
        by_rel[e.get("relation")] = by_rel.get(e.get("relation"), 0) + 1
    for r in C11_RELATIONS:
        want = C11_COUNTS[r.lower()]
        if by_rel.get(r, 0) != want:
            chk.fail(f"c11.2 {r} edges {by_rel.get(r, 0)} != {want}")
    # REVIEW_REQUIRED is decision-record state minus promotions settled on the
    # two RR edges (derived, not frozen: promotion of an RR edge consumes it)
    expected_rr = sum(1 for k, st in authored_states.items()
                      if st == "REVIEW_REQUIRED" and k not in promo_entries)
    if sum(1 for e in edges if e.get("validation_status") == "REVIEW_REQUIRED") \
            != expected_rr:
        chk.fail(f"c11.2 REVIEW_REQUIRED edge count mismatch (expected "
                 f"{expected_rr} from decisions-promotions)")

    universe = set(nodes) | set(C11_SCOPE_SPS) | set(prs)
    seen = set()
    prereq = {}
    part_of_derived = set()
    for e in edges:
        src, rel, tgt = e.get("source"), e.get("relation"), e.get("target")
        where = f"edge {src} -[{rel}]-> {tgt}"
        if rel not in C11_RELATIONS:
            chk.fail(f"c11.1 {where}: unknown relation type")
            continue
        if src == tgt:
            chk.fail(f"c11.8 {where}: self-edge")
        key = (src, rel, tgt)
        if key in seen:
            chk.fail(f"c11.8 {where}: duplicate edge")
        seen.add(key)
        for end in (src, tgt):
            if end not in universe:
                chk.fail(f"c11.7 {where}: endpoint {end!r} not in the pilot "
                         f"node universe")
        if e.get("validation_status") not in C11_EDGE_STATES:
            chk.fail(f"c11.10 {where}: validation_status "
                     f"{e.get('validation_status')!r} (operator-only promotion)")
        else:
            status = e.get("validation_status")
            promo = promo_entries.get(key)
            if status == "HUMAN_VALIDATED":
                if rel == "PART_OF":
                    chk.fail(f"c11.10 {where}: PART_OF cannot be "
                             f"HUMAN_VALIDATED (derived edge; node promotion "
                             f"pathway not built)")
                elif not promo:
                    chk.fail(f"c11.10 {where}: HUMAN_VALIDATED without a "
                             f"matching promotion record in "
                             f"scripts/c11_promotions.yaml (operator-only "
                             f"promotion; graph/promotions mismatch)")
                elif (e.get("validated_by") != promo.get("validated_by")
                      or e.get("validated_date") != promo.get("validated_date")):
                    chk.fail(f"c11.10 {where}: attribution mismatch vs the "
                             f"promotion record (graph: "
                             f"{e.get('validated_by')!r}/"
                             f"{e.get('validated_date')!r}; record: "
                             f"{promo.get('validated_by')!r}/"
                             f"{promo.get('validated_date')!r})")
            elif promo and rel != "PART_OF":
                chk.fail(f"c11.10 {where}: promotion recorded but edge not "
                         f"promoted (stale graph — re-run "
                         f"scripts/c11_concept_pilot.py)")
            # status drift vs the frozen decision record + promotions
            if rel != "PART_OF":
                if key not in authored_states:
                    chk.fail(f"c11.10 {where}: not authored in any "
                             f"decision record of the registry "
                             f"(hand-injected edge)")
                else:
                    want_status = ("HUMAN_VALIDATED" if promo
                                   else authored_states[key])
                    if status != want_status:
                        chk.fail(f"c11.10 {where}: status drift — decision "
                                 f"record+promotions say {want_status!r}, "
                                 f"graph says {status!r}")
        if e.get("validation_status") == "REVIEW_REQUIRED" \
                and not e.get("ambiguity_note"):
            chk.fail(f"c11.1 {where}: REVIEW_REQUIRED requires ambiguity_note")
        if e.get("confidence") not in C11_BANDS:
            chk.fail(f"c11.1 {where}: confidence {e.get('confidence')!r}")
        prov = e.get("provenance") or {}
        for k in ("tier", "model_version", "extraction_pass", "derivation_method",
                  "derivation_notes", "upstream", "generated_date"):
            if not prov.get(k):
                chk.fail(f"c11.3 {where}: provenance.{k} missing")
        if prov.get("tier") != "AI_SUGGESTED":
            chk.fail(f"c11.3 {where}: tier must be AI_SUGGESTED")
        if prov.get("derivation_method") not in C11_DERIVATION_CAPS:
            chk.fail(f"c11.3 {where}: derivation_method not in vocabulary")
        else:
            cap = C11_DERIVATION_CAPS[prov["derivation_method"]]
            rank = {"low": 0, "medium": 1, "high": 2}
            if rank[e["confidence"]] > rank[cap]:
                chk.fail(f"c11.9 {where}: confidence exceeds cap {cap!r}")

        sn, tn = nodes.get(src), nodes.get(tgt)
        if rel == "PART_OF":
            if not (sn and sn.get("family") == "CONCEPT"):
                chk.fail(f"c11.8 {where}: PART_OF source must be a CONCEPT")
            if tgt not in C11_SCOPE_SPS:
                chk.fail(f"c11.5 {where}: PART_OF target must be an "
                         f"in-scope SP (pilot or batch 1)")
            if e.get("role") not in C11_ROLES:
                chk.fail(f"c11.1 {where}: PART_OF role {e.get('role')!r}")
            part_of_derived.add((src, tgt, e.get("role")))
        elif rel in C11_MISCONCEPTION_RELATIONS:
            if not (sn and sn.get("family") == "MISCONCEPTION"):
                chk.fail(f"c11.8 {where}: source must be MISCONCEPTION-family")
            want = ("ERRONEOUS_BELIEF" if rel == "MISCONCEPTION_OF"
                    else "WRONG_ANSWER_PATTERN")
            if rel != "REMEDIATED_BY" and sn and sn.get("pattern_class") != want:
                chk.fail(f"c11.8 {where}: pattern_class "
                         f"{sn.get('pattern_class')!r} does not match {rel} "
                         f"(frozen triple distinction)")
            if not (tn and tn.get("family") == "CONCEPT"):
                chk.fail(f"c11.8 {where}: target must be a CONCEPT")
        elif rel == "EXPLAINED_BY":
            if not (sn and sn.get("family") == "CONCEPT" and tn
                    and tn.get("family") == "CONCEPT"):
                chk.fail(f"c11.8 {where}: EXPLAINED_BY must be CONCEPT->CONCEPT")
        elif rel == "REQUIRES_PREREQUISITE":
            if not (sn and sn.get("family") == "CONCEPT") and src not in prs:
                chk.fail(f"c11.8 {where}: source must be a concept or practical")
            if not (tn and tn.get("family") == "CONCEPT"):
                chk.fail(f"c11.8 {where}: target must be a CONCEPT")
            prereq.setdefault(src, set()).add(tgt)
        elif rel in ("RELATED_TO", "COMMONLY_CONFUSED_WITH"):
            if not (sn and tn and sn.get("family") == "CONCEPT"
                    and tn.get("family") == "CONCEPT"):
                chk.fail(f"c11.8 {where}: {rel} must be CONCEPT->CONCEPT")

        # anchor admissibility (rule 2 / §11: NOTE anchors must resolve through
        # T-C10 HUMAN_VALIDATED coverage of an attached SP of source or target;
        # MARK_SCHEME anchors are misconception-class only — this is the gate
        # that makes premise+consequence aggregation from uncovered notes fail)
        attached = set()
        for n_ in (sn, tn):
            if n_ and n_.get("family") == "CONCEPT":
                attached |= {a["code"] for a in n_.get("spec_points") or []}
        if src in prs:
            attached.add(prs[src]["spec_point"])
        ok = False
        for a in e.get("evidence") or []:
            _c11_anchor_check(chk, a, where, idx, sps)
            kind, relf, quote = a.get("kind"), a.get("file"), a.get("quote")
            if kind == "MARK_SCHEME":
                if rel in C11_MISCONCEPTION_RELATIONS:
                    ok = True
                else:
                    chk.fail(f"c11.6 {where}: MARK_SCHEME anchor inadmissible "
                             f"for {rel} (assessment evidence is "
                             f"misconception-class only)")
            elif kind == "SPEC":
                if any(c11_norm(quote) in c11_norm(sps[sp]["official_wording"])
                       for sp in attached if sp in sps):
                    ok = True
            elif kind == "NOTE":
                if any(sp in idx.get(relf, set()) for sp in attached):
                    ok = True
        if not ok:
            chk.fail(f"c11.6 {where}: no anchor is admissible (NOTE anchors "
                     f"must HUMAN_VALIDATED-map to an attached SP of the "
                     f"source/target; SPEC quotes must sit inside an attached "
                     f"SP's wording)")

    # PART_OF set must equal the attachments declared in concepts.yaml
    declared = set()
    for code, n in nodes.items():
        if n.get("family") == "CONCEPT":
            for att in n.get("spec_points") or []:
                declared.add((code, att["code"], att.get("role")))
    if part_of_derived != declared:
        chk.fail(f"c11.7 PART_OF edges != concepts.yaml attachments "
                 f"(missing {sorted(declared - part_of_derived)[:3]}, "
                 f"extra {sorted(part_of_derived - declared)[:3]})")

    # §18 promotions are audited BOTH ways: every promotion entry must appear
    # in the graph as HUMAN_VALIDATED with the exact recorded attribution
    # (catches stale graphs after a promotion was recorded or a removal)
    for key, p in sorted(promo_entries.items()):
        if key not in seen:
            chk.fail(f"c11.13 promotion for {key[0]} {key[1]} {key[2]} has no "
                     f"edge in the graph (stale or corrupted promotion record)")
            continue
        ge = next(e for e in edges if (e.get("source"), e.get("relation"),
                                       e.get("target")) == key)
        if ge.get("validation_status") != "HUMAN_VALIDATED":
            chk.fail(f"c11.13 promotion for {key[0]} {key[1]} {key[2]} not "
                     f"reflected in the graph (status "
                     f"{ge.get('validation_status')!r} — regenerate)")
    n_promoted = sum(1 for e in edges
                     if e.get("validation_status") == "HUMAN_VALIDATED")
    if promo_entries:
        if meta.get("promotion_record") != "scripts/c11_promotions.yaml":
            chk.fail("c11.13 edges meta.promotion_record must be "
                     "scripts/c11_promotions.yaml when promotions exist")
        if counts.get("promoted_edges") != n_promoted:
            chk.fail(f"c11.13 meta.counts.promoted_edges "
                     f"{counts.get('promoted_edges')} != actual {n_promoted}")
        if counts.get("human_validated_edges") != n_promoted:
            chk.fail(f"c11.13 meta.counts.human_validated_edges "
                     f"{counts.get('human_validated_edges')} != actual "
                     f"{n_promoted}")

    # acyclicity of REQUIRES_PREREQUISITE
    color = {}

    def dfs(u):
        color[u] = 1
        for v in sorted(prereq.get(u, ())):
            if color.get(v) == 1:
                return [u, v]
            if color.get(v, 0) == 0:
                cyc = dfs(v)
                if cyc:
                    return cyc
        color[u] = 2
        return None

    for u in sorted(prereq):
        if color.get(u, 0) == 0:
            cyc = dfs(u)
            if cyc:
                chk.fail(f"c11.8 REQUIRES_PREREQUISITE cycle: {cyc}")
                break
    return chk


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--graph", default=str(GRAPH_DEFAULT))
    ap.add_argument("--notes-root", default=str(NOTES_ROOT_DEFAULT))
    args = ap.parse_args()
    graph_dir = Path(args.graph)

    data = load_all(graph_dir)
    results = []
    results.append(check_meta(data))
    pt_chk, point_codes = check_spec_points(data)
    results.append(pt_chk)
    tp_chk, topic_codes, sub_codes, sub_members = check_topics(data, point_codes)
    results.append(tp_chk)
    results.append(check_relationships(data, point_codes, topic_codes, sub_codes,
                                        sub_members))
    results.append(check_command_words(data))
    results.append(check_practicals(data, point_codes))
    results.append(check_assessment(data))
    results.append(check_namespace_prose(data))
    results.append(check_notes_mapping(data, point_codes, sub_codes,
                                       notes_root=args.notes_root))
    # groups 10-11: T-C11 pilot concept graph (reads the three c11 files from
    # the same graph dir; T-C10 crosscheck always uses the REAL notes root so
    # negative tests can corrupt the graph copy alone)
    c11 = load_c11(graph_dir)
    results.append(check_c11_concepts(c11, data))
    results.append(check_c11_concept_edges(c11, data))

    total_fail = 0
    for chk in results:
        if chk.ok:
            print(f"PASS  {chk.name}")
        else:
            print(f"FAIL  {chk.name} ({len(chk.failures)} issue(s)):")
            for msg in chk.failures[:20]:
                print(f"      - {msg}")
            if len(chk.failures) > 20:
                print(f"      ... and {len(chk.failures) - 20} more")
            total_fail += len(chk.failures)
    print()
    if total_fail:
        print(f"graph_check: {total_fail} failure(s) across "
              f"{sum(1 for c in results if not c.ok)} check group(s).")
        sys.exit(1)
    n_points = len(point_codes)
    c11_promoted = sum(1 for e in c11["concept_edges.yaml"]["edges"]
                       if e.get("validation_status") == "HUMAN_VALIDATED")
    print(f"graph_check: ALL PASS — {n_points} spec points, "
          f"{len(topic_codes)} topics, {len(sub_codes)} subtopics, "
          f"{COUNTS['edges']} edges, {COUNTS['command_words']} command words, "
          f"{COUNTS['practicals']} practicals, {COUNTS['papers']} papers; "
          f"T-C11 store (pilot + §16 batches 1-2): {C11_COUNTS['nodes']} concept "
          f"nodes, "
          f"{C11_COUNTS['edges']} concept edges "
          f"({C11_COUNTS['part_of']} PART_OF + "
          f"{C11_COUNTS['edges'] - C11_COUNTS['part_of']} semantic), "
          f"{c11_promoted} HUMAN_VALIDATED (operator promotions; 0 from "
          f"generation; batch-1 verdicts applied session 48; batch-2 "
          f"verdicts applied session 50 — nodes have no §18 pathway), "
          f"negative control "
          f"{C11_NEGATIVE_CONTROL} "
          f"uncovered.")


if __name__ == "__main__":
    main()
